exclude :test_invalid_escape_string, "expected: [[1, 1], :on_tstring_content, \"\\n\" + \"hello\", BEG]"
exclude :test_lexer_scan_with_syntax_error, "needs investigation"
exclude :test_raise_errors_keyword, "needs investigation"
exclude :test_slice, "NoMethodError: undefined method 'slice' for class Prism::Translation::Ripper"
exclude :test_stack_at_on_heredoc_beg, "<[:on_ident, :on_sp, :on_heredoc_beg]> expected but was <[:on_ident, :on_sp, :on_heredoc_beg, :on_heredoc_end]>."
exclude :test_token_aftr_error_heredoc, "[#<Prism::Translation::Ripper::Lexer::Elem:    on_heredoc_beg@1:0"
exclude :test_trailing_on_embexpr_end, "<[[1, 17], :on_embexpr_end, \"}\", ARG]> expected but was <[[1, 17], :on_rbrace, \"}\", END]>."
