exclude :test_heredoc_inside_block_param, "<\"a do |b\\n\" + \"  <<-C\\n\" + \"  C\\n\" + \"  |\\n\" + \"end\\n\"> expected but was <\"ado|b\\n\" + \"<<-C\\n\" + \"  C\\n\" + \"|\\n\" + \"end\\n\">."
exclude :test_heredoc_unterminated_interpolation, "Expected \"\" to include \"+1\"."
exclude :test_invalid_escape_string, "expected: [[1, 1], :on_tstring_content, \"\\n\" + \"hello\", BEG]"
exclude :test_lexer_scan_with_syntax_error, "needs investigation"
exclude :test_raise_errors_keyword, "needs investigation"
exclude :test_slice, "NoMethodError: undefined method 'slice' for class Prism::Translation::Ripper"
exclude :test_spaces_at_eof, "<\"1\\n\" + \"\\t \\t\"> expected but was <\"1\\n\">."
exclude :test_stack_at_on_heredoc_beg, "<[:on_ident, :on_sp, :on_heredoc_beg]> expected but was <[:on_ident, :on_heredoc_beg, :on_heredoc_end]>."
exclude :test_token_aftr_error_heredoc, "[#<Prism::Translation::Ripper::Lexer::Elem:    on_heredoc_beg@1:0"
exclude :test_tokenize_with_here_document, "<\"\\n\" + \"<<A + \\\"hello\\n\" + \"A\\n\" + \"world\\\"\\n\"> expected but was <\"\\n\" + \"<<A+\\\"hello\\n\" + \"A\\n\" + \"world\\\"\\n\">."
exclude :test_trailing_on_embexpr_end, "<[[1, 17], :on_embexpr_end, \"}\", ARG]> expected but was <[[1, 17], :on_rbrace, \"}\", END]>."
