exclude :test_invalid_escape_string, "expected: [[1, 1], :on_tstring_content, \"\\n\" + \"hello\", BEG]"
exclude :test_lex_with_syntax_error_and_heredoc, "<[[5, 0], :on_heredoc_end, \"EOS\\n\", BEG]> expected but was <[[5, 0], :on_heredoc_end, \"EOS\\n\", END]>."
exclude :test_lexer_scan_with_syntax_error, "needs investigation"
exclude :test_nested_heredoc, "expected: [[5, 0], :on_heredoc_end, \"  H2\\n\", BEG]"
exclude :test_raise_errors_keyword, "needs investigation"
exclude :test_slice, "NoMethodError: undefined method 'slice' for class Prism::Translation::Ripper"
exclude :test_spaces_at_eof, "expected: [[2, 0], :on_sp, \"\\t \\t\", END]"
exclude :test_token_aftr_error_heredoc, "[#<Prism::Translation::Ripper::Lexer::Elem:    on_heredoc_beg@1:0"
exclude :test_trailing_on_embexpr_end, "<[[1, 17], :on_embexpr_end, \"}\", ARG]> expected but was <[[1, 17], :on_rbrace, \"}\", END]>."
