exclude :test_arg_ambiguous, "undefined symbol: rb_str_new_parser_string"
exclude :test_array, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_assign_error_const, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_assign_error_const_qualified, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_assign_error_const_toplevel, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_block_variables, "<\"[fcall(proc,[],&block([],[unary(!,ref(y))]))]\"> expected but was <\"[fcall(proc,[],&block([],[unary(!,vcall(y))]))]\">."
exclude :test_bodystmt, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_endless_def, "<{on_def: true, on_parse_error: true}> expected but was <{on_def: true}>."
exclude :test_endless_defs, "<{on_defs: true, on_parse_error: true}> expected but was <{on_defs: true}>."
exclude :test_event_coverage, "Expected [:arg_ambiguous,"
exclude :test_field, "undefined symbol: rb_id_attrset"
exclude :test_for, "undefined symbol: rb_make_temporary_id"
exclude :test_heredoc, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_heredoc_dedent, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_local_variables, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_params, "undefined symbol: rb_make_temporary_id"
exclude :test_params_mlhs, "undefined symbol: rb_make_temporary_id"
exclude :test_params_mlhs_add, "undefined symbol: rb_make_temporary_id"
exclude :test_params_mlhs_add_post, "undefined symbol: rb_make_temporary_id"
exclude :test_params_mlhs_add_star, "undefined symbol: rb_make_temporary_id"
exclude :test_params_mlhs_new, "undefined symbol: rb_make_temporary_id"
exclude :test_params_mlhs_paren, "undefined symbol: rb_make_temporary_id"
exclude :test_qsymbols_add, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_qwords_add, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_regexp_add, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_regexp_literal, "undefined symbol: rb_str_new_parser_string"
exclude :test_regexp_new, "undefined symbol: rb_str_new_parser_string"
exclude :test_rescue_class, "Expected /rescue\\(\\[ref\\(RuntimeError\\)\\],var_field\\(e\\),\\[2\\]\\)/ to match \"[begin(bodystmt([void(),1],rescue([vcall(RuntimeError)],var_field(e),[2])))]\"."
exclude :test_return_out_of_compile_error_no_memory_leak, "| ERROR: truffleruby: invalid option --parser=parse.y  (Use --help for usage instructions.)"
exclude :test_return_out_of_warn_no_memory_leak, "| ERROR: truffleruby: invalid option --parser=parse.y  (Use --help for usage instructions.)"
exclude :test_string_add, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_string_concat, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_string_content, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_string_dvar, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_string_embexpr, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_symbols_add, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_warn_duplicated_hash_keys, "undefined symbol: rb_node_sym_string_val"
exclude :test_warn_mismatched_indentations, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_warning_duplicated_when_clause, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_word_add, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_word_new, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_words_add, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_xstring_add, "undefined symbol: rb_str_new_mutable_parser_string"
