exclude :test_alias_error, "<\"[aliaserr($1)]\"> expected but was <\"\">."
exclude :test_anonymous_block_forwarding, "Expected /no\\ anonymous\\ block\\ parameter/ to match \"\"."
exclude :test_anonymous_keyword_rest_forwarding, "def b; c(**) end."
exclude :test_anonymous_rest_forwarding, "def b; c(*) end."
exclude :test_assign_error, "<true> expected but was <false>."
exclude :test_assign_error_backref, "<[:on_assign_error]> expected but was <[]>."
exclude :test_assign_error_const, "<true> expected but was <false>."
exclude :test_assign_error_const_qualified, "<true> expected but was <false>."
exclude :test_assign_error_const_toplevel, "<true> expected but was <false>."
exclude :test_blockarg, "<true> expected but was <false>."
exclude :test_endless_def, "<{on_def: true, on_parse_error: true}> expected but was <{on_parse_error: true}>."
exclude :test_endless_defs, "<{on_defs: true, on_parse_error: true}> expected but was <{on_parse_error: true}>."
exclude :test_event_coverage, "retain-on-retag fails on rerun after retag"
exclude :test_heredoc, "<true> expected but was <false>."
exclude :test_ignored_nl, "<[\"\\n\"]> expected but was <[]>."
exclude :test_invalid_class_variable_name, "<\"'@@1' is not allowed as a class variable name\"> expected but was <\"\">."
exclude :test_invalid_global_variable_name, "<\"'$%' is not allowed as a global variable name\"> expected but was <\"\">."
exclude :test_invalid_instance_variable_name, "<\"'@1' is not allowed as an instance variable name\"> expected but was <\"\">."
exclude :test_magic_comment, "<[:on_magic_comment, \"bug_5753\", \"ruby-dev:44984\"]> expected but was <[:on_magic_comment, \"bug-5753\", \"ruby-dev:44984\"]>."
exclude :test_operator_ambiguous, "<true> expected but was <false>."
exclude :test_param_error, "<true> expected but was <false>."
exclude :test_retry, "<true> expected but was <false>."
exclude :test_unterminated_heredoc, "Expected /can't\\ find\\ string\\ \"a\"\\ anywhere\\ before\\ EOF/ to match \"\"."
exclude :test_unterminated_regexp, "<\"unterminated regexp meets end of file\"> expected but was <\"\">."
exclude :test_warn_cr_in_middle, "warning expected"
exclude :test_warn_duplicated_hash_keys, "warning expected"
exclude :test_warn_mismatched_indentations, "<[\"if\", \"end\", 1]> expected but was <[nil, nil, nil]>."
exclude :test_warning_duplicated_when_clause, "warning expected"
exclude :test_warning_ignored_magic_comment, "warning expected"
exclude :test_warning_invalid_magic_comment, "warning expected"
