exclude :test_block_variables, "<\"[fcall(proc,[],&block([],[unary(!,ref(y))]))]\"> expected but was <\"[fcall(proc,[],&block([],[unary(!,vcall(y))]))]\">."
exclude :test_endless_def, "<{on_def: true, on_parse_error: true}> expected but was <{on_def: true}>."
exclude :test_endless_defs, "<{on_defs: true, on_parse_error: true}> expected but was <{on_defs: true}>."
exclude :test_event_coverage, "Expected [:field, :for] to be empty."
exclude :test_field, "undefined symbol: rb_id_attrset"
exclude :test_for, "undefined symbol: rb_make_temporary_id"
exclude :test_local_variables, "<\"[assign(var_field(w),1),binary(ref(w),/,25)]\"> expected but was <\"[assign(var_field(w),1),binary(vcall(w),/,25)]\">."
exclude :test_params, "undefined symbol: rb_make_temporary_id; retain-on-retag: only happens when running all Ripper test files together"
exclude :test_params_mlhs, "undefined symbol: rb_make_temporary_id"
exclude :test_params_mlhs_add, "undefined symbol: rb_make_temporary_id"
exclude :test_params_mlhs_add_post, "undefined symbol: rb_make_temporary_id"
exclude :test_params_mlhs_add_star, "undefined symbol: rb_make_temporary_id"
exclude :test_params_mlhs_new, "undefined symbol: rb_make_temporary_id"
exclude :test_params_mlhs_paren, "undefined symbol: rb_make_temporary_id"
exclude :test_rescue_class, "Expected /rescue\\(\\[ref\\(RuntimeError\\)\\],var_field\\(e\\),\\[2\\]\\)/ to match \"[begin(bodystmt([void(),1],rescue([vcall(RuntimeError)],var_field(e),[2])))]\"."
