exclude :test_CHAR, "<[]> expected but was <[\"?\\\\\"]>."
exclude :test_error_token, "<\"\"> expected but was <nil>."
exclude :test_heredoc_end, "<[]> expected but was <[\"\"]>."
exclude :test_invalid_char, "NoMethodError: undefined method '[]' for nil"
exclude :test_invalid_escape, "<[:on_parse_error, \"Invalid escape character syntax\", \"\\\\C-あ\"]> expected but was <nil>."
exclude :test_invalid_hex_escape_regexp, "<[\"\\\\x\", \"U\"]> expected but was <[\"\\\\xU\"]>."
exclude :test_invalid_hex_escape_string, "<[\"\\\\x\", \"U\"]> expected but was <[\"\\\\xU\"]>."
exclude :test_lex, "<[[[1, 0], :on_kw, \"def\", FNAME],"
exclude :test_location, "<\" \"> expected but was <\"\">."
exclude :test_sp, "<[\" \"]> expected but was <[]>."
exclude :test_tokenize, "<[\"1\", \";\", \"def\", \" \", \"m\", \"(\", \"arg\", \")\", \"end\"]> expected but was <[\"1\", \";\", \"def\", \"m\", \"(\", \"arg\", \")\", \"end\"]>."
exclude :test_words_sep, "<[\"\\n\", \"\\n\", \"\\n\", \" \", \" \", \" \"]> expected but was <[\"\\n\" + \"\\n\", \"\\n\" + \" \", \" \", \" \"]>."
