exclude :test_CHAR, "<[]> expected but was <[\"?\\\\\"]>."
exclude :test_error_token, "<\"\"> expected but was <nil>."
exclude :test_event_coverage, "retain-on-retag fails on rerun after retag"
exclude :test_invalid_char, "NoMethodError: undefined method '[]' for nil"
exclude :test_invalid_escape, "<[:on_parse_error, \"Invalid escape character syntax\", \"\\\\C-あ\"]> expected but was <nil>."
exclude :test_invalid_hex_escape_regexp, "<[\"\\\\x\", \"U\"]> expected but was <[\"\\\\xU\"]>."
exclude :test_invalid_hex_escape_string, "<[\"\\\\x\", \"U\"]> expected but was <[\"\\\\xU\"]>."
exclude :test_lex, "<[[[1, 0], :on_heredoc_beg, \"<<EOS\", BEG],"
