exclude :test_command, "<[:program,"
exclude :test_compile_error, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_dsym, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_heredoc_content, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_hshptn, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_named_with_default, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_params_mlhs, "transient"
exclude :test_pattern_matching_178, " case 0; in 0 if a; end ."
exclude :test_pattern_matching_186, " case 0; in 0 unless a; end ."
exclude :test_pattern_matching_314, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_pattern_matching_326, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_pattern_matching_512, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_pattern_matching_515, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_pattern_matching_526, " case 0; in [*a]; a; end ."
exclude :test_pattern_matching_534, " case 0; in {a:}; a; end ."
exclude :test_regexp_content, "undefined symbol: rb_str_new_parser_string"
exclude :test_regexp_named_capture, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_squiggly_heredoc, "undefined symbol: rb_str_new_mutable_parser_string"
exclude :test_squiggly_heredoc_with_interpolated_expression, "undefined symbol: rb_str_new_mutable_parser_string"
