exclude :test_command, "<[:program,"
exclude :test_compile_error, "JVM crash; SIGBUS: C  [ripper.so+0x3b8c7]  ripper_yyparse+0x18377"
exclude :test_named_with_default, "undefined symbol: rb_make_temporary_id"
exclude :test_params_mlhs, "transient"
exclude :test_patt, "slow: 54.01s on truffleruby 34.0.0-dev-0b9bf975, like ruby 3.4.7, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 9800X3D 8-Core Processor: ( 16 vCPUs)"
exclude :test_pattern_matching_178, " case 0; in 0 if a; end ."
exclude :test_pattern_matching_186, " case 0; in 0 unless a; end ."
exclude :test_pattern_matching_526, " case 0; in [*a]; a; end ."
exclude :test_pattern_matching_534, " case 0; in {a:}; a; end ."
exclude :test_regexp_named_capture, "JVM crash; SIGBUS: C  [ripper.so+0x3b8c7]  ripper_yyparse+0x18377"
