exclude :test_command, "<[:program,"
exclude :test_compile_error, "undefined symbol: rb_node_regx_string_val"
exclude :test_named_with_default, "undefined symbol: rb_make_temporary_id"
exclude :test_params_mlhs, "transient"
exclude :test_patt, "slow: 54.01s on truffleruby 34.0.0-dev-0b9bf975, like ruby 3.4.7, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 9800X3D 8-Core Processor: ( 16 vCPUs)"
exclude :test_pattern_matching_178, " case 0; in 0 if a; end ."
exclude :test_pattern_matching_186, " case 0; in 0 unless a; end ."
exclude :test_pattern_matching_314, "undefined symbol: rb_node_sym_string_val"
exclude :test_pattern_matching_326, "undefined symbol: rb_node_sym_string_val"
exclude :test_pattern_matching_512, "undefined symbol: rb_node_sym_string_val"
exclude :test_pattern_matching_515, "undefined symbol: rb_node_sym_string_val"
exclude :test_pattern_matching_526, " case 0; in [*a]; a; end ."
exclude :test_pattern_matching_534, " case 0; in {a:}; a; end ."
exclude :test_regexp_named_capture, "undefined symbol: rb_node_regx_string_val"
