source 'https://rubygems.org'

# Exact versions with known working combination
gem 'ast', '2.4.2'
gem 'parallel', '1.22.1'
gem 'parser', '3.1.2.1'
gem 'rainbow', '3.1.1'
gem 'regexp_parser', '2.5.0'
gem 'rexml', '3.2.5'
gem 'rubocop', '1.36.0'
gem 'rubocop-ast', '1.21.0'
gem 'ruby-progressbar', '1.11.0'
gem 'unicode-display_width', '2.2.0'

# Needed because of bundled_gems.rb on e.g. Ruby 3.3
gem 'base64'
gem 'ostruct'
gem 'racc'
