exclude :test_get_symbol_or_name, "RDoc::Error: Name or symbol expected (got #<struct RDoc::Parser::RipperStateLex::Token line_no=1, char_no=6, kind=:on_int, text=\"+5\", state=END>)"
exclude :test_parse_constant_the_same_of_outside, "<\"<span class=\\\"ruby-keyword\\\">def</span> <span class=\\\"ruby-keyword\\\">self</span>.<span class=\\\"ruby-identifier ruby-title\\\">foo</span>\\n\" +"
exclude :test_parse_instance_operation_method, "<\"  <span class=\\\"ruby-keyword\\\">def</span> <span class=\\\"ruby-keyword\\\">self</span>.<span class=\\\"ruby-identifier ruby-title\\\">&amp;</span> <span class=\\\"ruby-keyword\\\">end</span>\\n\" +"
exclude :test_parse_meta_method, "<\"add_my_method :foo\"> expected but was <\"add_my_method:foo\">."
exclude :test_parse_method, "<\"def foo\"> expected but was <\"deffoo\">."
exclude :test_parse_method_no_parens, "<\"(arg1, arg2 = {})\"> expected but was <\"(arg1,arg2={})\">."
exclude :test_parse_method_parameters_comment, "<\"(arg1, arg2)\"> expected but was <\"(arg1,arg2)\">."
exclude :test_parse_method_parameters_comment_continue, "<\"(arg1, arg2, arg3)\"> expected but was <\"(arg1,arg2,arg3)\">."
exclude :test_parse_method_parameters_with_paren_comment_continue, "<\"(arg1, arg2, arg3)\"> expected but was <\"(arg1,arg2,arg3)\">."
exclude :test_parse_method_utf8, "<\"def ω\"> expected but was <\"defω\">."
exclude :test_parse_mutable_heredocbeg, "<\"  <span class=\\\"ruby-keyword\\\">def</span> <span class=\\\"ruby-identifier ruby-title\\\">blah</span>()\\n\" +"
exclude :test_parse_on_ignored_nl_with_nil_text, "<\"<span class=\\\"ruby-keyword\\\">def</span> <span class=\\\"ruby-identifier ruby-title\\\">meth</span>\\n\" +"
exclude :test_parse_redefinable_methods, "<:on_ident> expected but was <:on_nl>."
exclude :test_parse_statements_complex_condition_in_for, "<\"<span class=\\\"ruby-keyword\\\">def</span> <span class=\\\"ruby-identifier ruby-title\\\">blah</span>()\\n\" +"
exclude :test_parse_statements_def_percent_string_pound, "<[{line_no: 2,"
exclude :test_parse_statements_identifier_constant, "<\"{\\n\" + \":foo => 'bar',\\n\" + \":x => 'y'\\n\" + \"}\"> expected but was <\"{\\n\" + \":foo=>'bar',\\n\" + \":x=>'y'\\n\" + \"}\">."
exclude :test_parse_statements_method_oneliner_with_regexp, "<\"<span class=\\\"ruby-keyword\\\">def</span> <span class=\\\"ruby-identifier ruby-title\\\">blah</span>() <span class=\\\"ruby-regexp\\\">/bar/</span> <span class=\\\"ruby-keyword\\\">end</span>\"> expected but was <\"<span class=\\\"ruby-keyword\\\">def</span><span class=\\\"ruby-identifier ruby-title\\\">blah</span>()<span class=\\\"ruby-regexp\\\">/bar/</span><span class=\\\"ruby-keyword\\\">end</span>\">."
exclude :test_parse_statements_postfix_if_after_heredocbeg, "<\"  <span class=\\\"ruby-keyword\\\">def</span> <span class=\\\"ruby-identifier ruby-title\\\">blah</span>()\\n\" +"
exclude :test_parse_syntax_error_code, "Expected /RDoc::Parser::Ruby\\ failure\\ around\\ line\\ 2\\ of\\n\\/tmp\\/RDocParserRubyTest20260118\\-1395350\\-qgmyh1\\n\\nclass\\ Invalid::@@Code\\n/ to match \"\\n\" +"
exclude :test_sanity_interpolation_crazy, "<\"\\\"\\\#{\\\"\\\#{\\\"a\\\")}\\\" if b}\\\"\"> expected but was <\"\\\"\\\#{\\\"\\\#{\\\"a\\\")}\\\"ifb}\\\"\">."
