exclude :test_call_ifunc_iseq_large_array_splat_fail, "NameError: uninitialized constant TestCall::Bug"
exclude :test_call_ifunc_iseq_large_array_splat_pass, "NameError: uninitialized constant TestCall::Bug"
exclude :test_call_op_asgn_keywords, "/b/b/e/main/test/mri/tests/ruby/test_call.rb:159:in `test_call_op_asgn_keywords'."
exclude :test_call_op_asgn_keywords_mutable, "/b/b/e/main/test/mri/tests/ruby/test_call.rb:320:in `test_call_op_asgn_keywords_mutable'."
exclude :test_call_rb_call_bmethod_large_array_splat_fail, "NameError: uninitialized constant TestCall::Bug"
exclude :test_call_rb_call_bmethod_large_array_splat_pass, "NameError: uninitialized constant TestCall::Bug"
exclude :test_call_rb_call_iseq_large_array_splat_fail, "NameError: uninitialized constant TestCall::Bug"
exclude :test_call_rb_call_iseq_large_array_splat_pass, "NameError: uninitialized constant TestCall::Bug"
exclude :test_kwsplat_block_eval_order, "<[{a:    #<Proc:0xe78 /b/b/e/main/test/mri/tests/ruby/test_call.rb:380 (lambda)>},"
exclude :test_kwsplat_block_order_op_asgn, "/b/b/e/main/test/mri/tests/ruby/test_call.rb:292:in `test_kwsplat_block_order_op_asgn'."
