exclude :test_load_ospath, "Encoding::CompatibilityError: incompatible encoding regexp match (Windows-31J regexp with UTF-8 string)"
exclude :test_loading_fifo_fd_leak, "very slow: 181.74s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_loading_fifo_threading_raise, "very slow: 180.47s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_loading_fifo_threading_success, "very slow: 180.49s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_private_in_wrapped_load, "NameError: undefined method `foo' for class `Object'"
exclude :test_public_in_wrapped_load, "NameError: undefined method `foo' for class `Object'"
exclude :test_relative_symlink_realpath, "<\"1\"> expected but was <\"2\">."
exclude :test_require_changed_home, "| <internal:core> core/kernel.rb:269:in `require': cannot load such file -- foo (LoadError)"
exclude :test_require_nonascii_path, "LoadError: cannot load such file -- enc/trans/single_byte"
exclude :test_require_nonascii_path_shift_jis, "LoadError: cannot load such file -- enc/trans/single_byte"
exclude :test_require_path_home_1, "| truffleruby: No such file or directory -- -w (LoadError)"
exclude :test_require_path_home_2, "| truffleruby: No such file or directory -- -w (LoadError)"
exclude :test_require_path_home_3, "| truffleruby: No such file or directory -- test_ruby_test_require20251202-4067500-ndh2dp.rb (LoadError)"
exclude :test_require_to_path_redefined_in_load_path, "| <internal:core> core/kernel.rb:269:in `require': cannot load such file -- foo (LoadError)"
exclude :test_require_to_str_redefined_in_load_path, "| <internal:core> core/kernel.rb:269:in `require': cannot load such file -- foo (LoadError)"
exclude :test_require_too_long_filename, "Expected 2 to be <= 1."
exclude :test_require_with_loaded_features_pop, "TypeError: no implicit conversion of nil into String"
