exclude :test_arity_error_message, "Expected Exception(ArgumentError) was raised, but the message doesn't match. Expected /required keyword: x\\)/ to match \"wrong number of arguments (given 1, expected 0)\"."
exclude :test_dig_method_missing_kwsplat, "TypeError: Object does not have #dig method"
exclude :test_keyword_splat_new, "<{a: 1}>"
exclude :test_keyword_splat_nil, "TypeError: no implicit conversion of NilClass into Hash"
exclude :test_keyword_splat_to_non_keyword_method, "<{a: 1}>"
exclude :test_large_kwsplat_to_method_taking_kw_and_kwsplat, "very slow: 121.23s on truffleruby 34.0.0-dev-0b9bf975, like ruby 3.4.7, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 9800X3D 8-Core Processor: ( 16 vCPUs)"
exclude :test_proc_ruby2_keywords, "expected: /Skipping set of ruby2_keywords flag for proc \\(proc accepts keywords or post arguments or proc does not accept argument splat\\)/"
exclude :test_rb_call_super_kw_method_missing_kwsplat, "NameError: uninitialized constant TestKeywordArguments::Bug"
exclude :test_rb_yield_block_kwsplat, "NameError: uninitialized constant TestKeywordArguments::Bug"
exclude :test_ruby2_keywords, "expected: /Skipping set of ruby2_keywords flag for bar \\(method accepts keywords or post arguments or method does not accept argument splat\\)/"
exclude :test_ruby2_keywords_post_arg, "expected: /Skipping set of ruby2_keywords flag for b \\(method accepts keywords or post arguments or method does not accept argument splat\\)/"
exclude :test_top_ruby2_keywords, "needs investigation"
