exclude :test_assign_in_conditional, "expected: /'= literal' in conditional/"
exclude :test_define_singleton_error, "Exception(SyntaxError) with message matches to /singleton method for literals/."
exclude :test_disallowed_class_variable, "/b/b/e/main/test/mri/tests/ruby/test_parse.rb:394:in `block in assert_disallowed_variable'."
exclude :test_disallowed_gloal_variable, "/b/b/e/main/test/mri/tests/ruby/test_parse.rb:394:in `block in assert_disallowed_variable'."
exclude :test_else_without_rescue, "[\"/b/b/e/main/test/mri/tests/ruby/test_parse.rb\", 23]."
exclude :test_error_def_in_argument, "-:7:in `<main>'."
exclude :test_error_line, "Message to pipe should end with a newline."
exclude :test_global_variable, "/b/b/e/main/test/mri/tests/ruby/test_parse.rb:901:in `test_global_variable'."
exclude :test_heredoc_unterminated_interpolation, "/b/b/e/main/test/mri/tests/ruby/test_parse.rb:1355:in `test_heredoc_unterminated_interpolation'."
exclude :test_location_of_invalid_token, "/b/b/e/main/test/mri/tests/ruby/test_parse.rb:1425:in `test_location_of_invalid_token'."
exclude :test_magic_comment, "[ArgumentError] exception expected, not #<SyntaxError: /b/b/e/main/test/mri/tests/ruby/test_parse.rb:786: unknown or invalid encoding in the magic comment>."
exclude :test_method_block_location, "<1103> expected but was <1101>."
exclude :test_method_location_in_rescue, "<1293> expected but was <1300>."
exclude :test_op_asgn1_with_block, "/b/b/e/main/test/mri/tests/ruby/test_parse.rb:527:in `test_op_asgn1_with_block'."
exclude :test_question, "SyntaxError: (eval):1: cannot eval() a String with binary encoding, with no magic encoding comment and containing a non-US-ASCII character: \\xFF"
exclude :test_shareable_constant_value_hash_with_keyword_splat, "NameError: uninitialized constant TestParse::Ractor"
exclude :test_shareable_constant_value_literal_const_refs, "NameError: uninitialized constant TestParse::Ractor"
exclude :test_shareable_constant_value_nested, "NameError: uninitialized constant TestParse::Ractor"
exclude :test_shareable_constant_value_nonliteral, "NameError: uninitialized constant TestParse::Ractor"
exclude :test_shareable_constant_value_simple, "NameError: uninitialized constant TestParse::Ractor"
exclude :test_shareable_constant_value_unfrozen, "NameError: uninitialized constant TestParse::Ractor"
exclude :test_shareable_constant_value_unshareable_literal, "NameError: uninitialized constant TestParse::Ractor"
exclude :test_string, "from the backslash through the invalid char."
exclude :test_truncated_source_line, "NoMethodError: undefined method `start_with?' for nil"
exclude :test_unclosed_unicode_escape_at_eol_bug_19750, "-:8:in `<main>'."
exclude :test_unexpected_eof, "/b/b/e/main/test/mri/tests/ruby/test_parse.rb:1421:in `test_unexpected_eof'."
exclude :test_unexpected_token_after_numeric, "/b/b/e/main/test/mri/tests/ruby/test_parse.rb:1363:in `test_unexpected_token_after_numeric'."
exclude :test_unused_variable, "expected: /あ/"
exclude :test_utf8_bom, "Exception raised: <#<SyntaxError: (eval):1: cannot eval() a String with binary encoding, with no magic encoding comment and containing a non-US-ASCII character: \\xEF>>"
exclude :test_yyerror_at_eol, "/b/b/e/main/test/mri/tests/ruby/test_parse.rb:1260:in `test_yyerror_at_eol'."
