exclude :test_bad_initialize_copy, "frozen."
exclude :test_implicit_respond_to_arity_3, "Expected Exception(ArgumentError) was raised, but the message doesn't match. <\"respond_to? must accept 1 or 2 arguments (requires 3)\"> expected but was <\"wrong number of arguments (given 2, expected 3)\">."
exclude :test_max_shape_variation_with_performance_warnings, "needs investigation"
exclude :test_method_missing, "[ArgumentError] exception expected, not #<NoMethodError: undefined method 'method_missing' for an instance of #<Class:0x958>>."
exclude :test_redefine_method_under_verbose, "needs investigation"
exclude :test_redefine_method_which_may_case_serious_problem, "needs investigation"
exclude :test_remove_instance_variable_re_embed, "Expected \"{\\\"address\\\":\\\"0x338\\\",\\\"class\\\":\\\"0x308\\\",\\\"memsize\\\":4,\\\"flags\\\":{},\\\"type\\\":\\\"OBJECT\\\",\\\"length\\\":3}\" to include \"\\\"embedded\\\":true\"."
exclude :test_remove_method, "needs investigation"
exclude :test_respond_to_missing, "<#<Method: #<Class:0xe78>#foobar(*rest) /b/b/e/main/test/mri/tests/ruby/test_object.rb:632>> expected but was <#<Method: #<Class:0xe78>#foobar(*rest) /b/b/e/main/test/mri/tests/ruby/test_object.rb:632>>."
