exclude :test_any_hash_fixable, "very slow: 178.88s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_fetch_error, "Expected /\\.\\.\\.\\z/ to match \"key not found: \\\"gumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumbygumby\\\"\"."
exclude :test_float_hash_random, "very slow: 70.52s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_huge_iter_level, "spurious; RuntimeError expected but nothing was raised."
exclude :test_inspect, "Encoding::CompatibilityError: incompatible encoding regexp match (UTF-8 regexp with Windows-31J string)"
exclude :test_integer_hash_random, "very slow: 69.57s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_inverse_hash, "<9011825271860307731> expected to be != to"
exclude :test_merge!, "FrozenError expected but nothing was raised."
exclude :test_recursive_hash_value_struct, "Exception raised: <#<SystemStackError: stack level too deep from java.nio.CharBuffer.<init>(CharBuffer.java:323)>>"
exclude :test_rehash2, "RuntimeError expected but nothing was raised."
exclude :test_reject, "Expected {1 => \"one\", 2 => false, true => \"true\", \"cat\" => 99}.instance_variable_defined?(:@foo) to return false."
exclude :test_symbol_hash_random, "slow: 43.82s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_transform_keys_bang, "<{false => 1, b: 2, c: 3}> expected but was <{false => 1}>."
exclude :test_transform_values_bang, "Exception(RuntimeError) with message matches to /rehash during iteration/."
exclude :test_update5, "FrozenError expected but nothing was raised."
exclude :test_update_modify_in_block, "Exception(RuntimeError) with message matches to /rehash during iteration/."
