exclude :test_Integer, "[Encoding::CompatibilityError] exception expected, not #<ArgumentError: invalid value for Integer(): 0>."
exclude :test_Integer_when_to_str, "TypeError: can't convert Object into Integer"
exclude :test_Integer_with_base, "TypeError expected but nothing was raised."
exclude :test_Integer_with_exception_keyword, "RuntimeError: "
exclude :test_Integer_with_invalid_exception, "ArgumentError expected but nothing was raised."
exclude :test_bitwise_and_with_integer_coercion, "TypeError: #<Class:0x4c8> can't be coerced into Integer"
exclude :test_bitwise_or_with_integer_coercion, "TypeError: #<Class:0x4f8> can't be coerced into Integer"
exclude :test_bitwise_xor_with_integer_coercion, "TypeError: #<Class:0x528> can't be coerced into Integer"
exclude :test_ceildiv, "NoMethodError: undefined method '-@' for #<Object:0x558>"
exclude :test_downto, "<-1> expected but was <nil>."
exclude :test_pow, "slow: 32.76s on truffleruby 34.0.0-dev-4fa3b117 (2026-01-31), like ruby 3.4.7, Interpreted JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor: ( 16 vCPUs)"
exclude :test_round, "<300> expected but was <200>."
exclude :test_upto, "<1> expected but was <nil>."
