exclude :test_defined_assignment, "<\"assignment\"> expected but was <\"expression\">."
exclude :test_defined_hash, "Expected \"expression\" to be nil."
exclude :test_defined_matchdata, "<nil> expected but was <\"global-variable\">."
exclude :test_defined_method_single_call, "<2> expected but was <3>."
exclude :test_defined_splat, "Expected \"expression\" to be nil."
exclude :test_respond_to, "expected: /deprecated method signature.*\\n.*respond_to\\? is defined here/"
exclude :test_top_level_constant_not_defined, "Expected \"constant\" to be nil."
