exclude :test_argument_error_location, "<\"main.rb:1:in 'block in <main>'\"> expected but was <\"main.rb:1:in 'block (2 levels) in <main>'\">."
exclude :test_arity_special, "<-1> expected but was <-2>."
exclude :test_body, "Exception raised: <#<NameError: uninitialized constant TestMethod::RubyVM>>"
exclude :test_callee, "Expected :\"<class:TestCallee>\" to be nil."
exclude :test_callee_top_level, "needs investigation"
exclude :test_caller_negative_level, "ArgumentError expected but nothing was raised."
exclude :test_clone, "TypeError: allocator undefined for Method"
exclude :test_clone_under_gc_compact_stress, "TypeError: allocator undefined for Method"
exclude :test_curry_from_proc, "Expected Exception(ArgumentError) was raised, but the message doesn't match. Expected /wrong number/ to match \"Wrong number of arguments (2 for 3)\"."
exclude :test_curry_from_proc_var_args, "NoMethodError: undefined method 'call' for an instance of Array"
exclude :test_curry_method, "Expected Exception(ArgumentError) was raised, but the message doesn't match. Expected /wrong number/ to match \"Wrong number of arguments (2 for 3)\"."
exclude :test_curry_var_args, "NoMethodError: undefined method 'call' for an instance of Array"
exclude :test_define_method, "Expected Exception(TypeError) was raised, but the message doesn't match. Expected /X\\u{1F431}/ to match \"#<Class:0x24f8> is not a symbol nor a string\"."
exclude :test_eq, "<#<Method: #<Object:0x2628>.foo() /home/eregon/code/trws/truffleruby/test/mri/tests/ruby/test_method.rb:191>> expected to be != to"
exclude :test_inspect, "<\"#<Method: #<Class:0x26c8>(#<Class:0x26b8>)#foo() /home/eregon/code/trws/truffleruby/test/mri/tests/ruby/test_method.rb:495>\"> expected but was <\"#<Method: #<Class:0x26c8>#foo() /home/eregon/code/trws/truffleruby/test/mri/tests/ruby/test_method.rb:495>\">."
exclude :test_instance_method, "Expected Exception(TypeError) was raised, but the message doesn't match. Expected /X\\u{1F431}/ to match \"no implicit conversion of Class into String\"."
exclude :test_method_list, "spurious; TypeError: no implicit conversion of Array into Integer"
exclude :test_method_parameters_inspect, "Expected \"#<Method: TestMethod#mo8(a, b=..., **, d, &e) /home/eregon/code/trws/truffleruby/test/mri/tests/ruby/test_method.rb:24>\" to include \"(a, b=..., *, d, &e)\"."
exclude :test_override_optimized_method_on_class_using_prepend, "NoMethodError: undefined method 'unpack1' for nil"
exclude :test_public_methods_with_extended, "spurious; <[:m1, :a]> expected but was <[:a, :m1]>."
exclude :test_singleton_method_included_or_prepended_bug_20620, "NameError: undefined singleton method 'foo' for Module"
exclude :test_super_method_bind_unbind_clone, "TypeError: allocator undefined for Method"
exclude :test_super_method_module, "NoMethodError: undefined method 'owner' for nil"
exclude :test_super_method_removed_public, "Expected #<UnboundMethod: #<Class:0x2d58>#foo() /home/eregon/code/trws/truffleruby/test/mri/tests/ruby/test_method.rb:1133> to be nil."
exclude :test_unbound_method_parameters_inspect, "Expected \"#<UnboundMethod: TestMethod#mo8(a, b=..., **, d, &e) /home/eregon/code/trws/truffleruby/test/mri/tests/ruby/test_method.rb:24>\" to include \"(a, b=..., *, d, &e)\"."
exclude :test_visibility, "<nil> expected but was <\"method\">."
exclude :test_warn_unused_block, "<2> expected but was <0>."
exclude :test_zsuper_method_redefined_bind_call, "<[:bar2]> expected but was <[:foo, :bar]>."
exclude :test_zsuper_method_removed, "<\"#<UnboundMethod: A#foo(arg=...) /home/eregon/code/trws/truffleruby/test/mri/tests/ruby/test_method.rb:1299>\"> expected but was <\"#<UnboundMethod: B#foo(arg=...) /home/eregon/code/trws/truffleruby/test/mri/tests/ruby/test_method.rb:1299>\">."
exclude :test_zsuper_method_removed_higher_method, "<\"#<UnboundMethod: A#foo(arg=...) /home/eregon/code/trws/truffleruby/test/mri/tests/ruby/test_method.rb:1341>\"> expected but was <\"#<UnboundMethod: B#foo(arg=...) /home/eregon/code/trws/truffleruby/test/mri/tests/ruby/test_method.rb:1341>\">."
