exclude :test_128_bit_integers, "NoMethodError: undefined method 'set_value' for an instance of IO::Buffer"
exclude :test_clear, "NoMethodError: undefined method 'clear' for an instance of IO::Buffer"
exclude :test_compare_different_size, "NoMethodError: undefined method '<' for nil"
exclude :test_compare_same_size, "NoMethodError: undefined method 'set_value' for an instance of IO::Buffer"
exclude :test_compare_zero_length, "NoMethodError: undefined method '<' for nil"
exclude :test_copy_null_destination, "NoMethodError: undefined method 'copy' for an instance of IO::Buffer"
exclude :test_copy_null_source, "NoMethodError: undefined method 'copy' for an instance of IO::Buffer"
exclude :test_copy_overlapped_bwd, "NoMethodError: undefined method 'copy' for an instance of IO::Buffer"
exclude :test_copy_overlapped_fwd, "NoMethodError: undefined method 'copy' for an instance of IO::Buffer"
exclude :test_each, "NoMethodError: undefined method 'size_of' for class IO::Buffer"
exclude :test_endian, "NameError: uninitialized constant IO::Buffer::LITTLE_ENDIAN"
exclude :test_get_set_value, "NoMethodError: undefined method 'set_value' for an instance of IO::Buffer"
exclude :test_get_set_values, "NoMethodError: undefined method 'set_values' for an instance of IO::Buffer"
exclude :test_get_string, "Exception(ArgumentError) with message matches to /bigger than the buffer size/."
exclude :test_inplace_operators, "FrozenError: can't modify frozen String: \"1234123412\""
exclude :test_integer_endianness_swapping, "NameError: uninitialized constant IO::Buffer::HOST_ENDIAN"
exclude :test_operators, "<#<IO::Buffer 0x????????????????+10 EXTERNAL READONLY SLICE>"
exclude :test_pread, "NoMethodError: undefined method 'pread' for an instance of IO::Buffer"
exclude :test_pread_offset, "NoMethodError: undefined method 'pread' for an instance of IO::Buffer"
exclude :test_pwrite, "NoMethodError: undefined method 'pwrite' for an instance of IO::Buffer"
exclude :test_pwrite_offset, "NoMethodError: undefined method 'pwrite' for an instance of IO::Buffer"
exclude :test_read, "NoMethodError: undefined method 'read' for an instance of IO::Buffer"
exclude :test_read_with_length_and_offset, "NoMethodError: undefined method 'read' for an instance of IO::Buffer"
exclude :test_read_with_with_length, "NoMethodError: undefined method 'read' for an instance of IO::Buffer"
exclude :test_read_with_with_offset, "NoMethodError: undefined method 'read' for an instance of IO::Buffer"
exclude :test_set_string_null_destination, "FrozenError: can't modify frozen String: \"\""
exclude :test_slice, "<\"Hello World\"> expected but was <\"\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\\x00\">."
exclude :test_slice_bounds_error, "ArgumentError expected but nothing was raised."
exclude :test_slice_readonly, "Expected #<IO::Buffer 0x????????????????+11>"
exclude :test_string_mapped_mutable, "NoMethodError: undefined method 'set_value' for an instance of IO::Buffer"
exclude :test_string_negative, "[ArgumentError] exception expected, not #<LocalJumpError: no block given>."
exclude :test_transfer_in_block, "RuntimeError: temporal unlocking already unlocked string"
exclude :test_values, "NoMethodError: undefined method 'set_values' for an instance of IO::Buffer"
exclude :test_write, "NoMethodError: undefined method 'write' for an instance of IO::Buffer"
exclude :test_write_with_length_and_offset, "NoMethodError: undefined method 'write' for an instance of IO::Buffer"
exclude :test_zero_length_get_set_values, "NoMethodError: undefined method 'get_values' for an instance of IO::Buffer"
