exclude :test_initialize_connect_timeout, "transient"
exclude :test_initialize_failure, "Expected /for\\ \"192\\.0\\.2\\.1\"\\ port\\ 8000/ to match \"Address not available - bind(2)\"."
exclude :test_initialize_resolv_timeout_with_connection_failure, "[Errno::ETIMEDOUT] exception expected, not #<ArgumentError: unknown keyword: :test_mode_settings>."
exclude :test_initialize_v4_hostname_resolved_earlier, "hangs"
exclude :test_initialize_v6_hostname_resolution_failed_and_v4_hostname_resolution_is_success, "hangs"
exclude :test_initialize_v6_hostname_resolved_earlier, "hangs"
exclude :test_initialize_v6_hostname_resolved_earlier_and_v6_server_is_not_listening, "hangs"
exclude :test_initialize_v6_hostname_resolved_in_resolution_delay, "hangs"
exclude :test_initialize_v6_hostname_resolved_later_and_v6_server_is_not_listening, "hangs"
exclude :test_initialize_with_connection_failure_after_hostname_resolution_failure, "[Errno::ECONNREFUSED] exception expected, not #<ArgumentError: unknown keyword: :test_mode_settings>."
exclude :test_initialize_with_hostname_resolution_failure_after_connection_failure, "[Errno::ECONNREFUSED] exception expected, not #<ArgumentError: unknown keyword: :test_mode_settings>."
exclude :test_inspect, "Expected /AF_INET/ to match \"#<TCPServer:fd 38>\"."
exclude :test_recvfrom, "SocketError: need IPv4 or IPv6 address"
exclude :test_tcp_initialize_open_timeout, "[IO::TimeoutError] exception expected, not #<ArgumentError: unknown keywords: :open_timeout, :test_mode_settings>."
