exclude :test_array_empty?, "needs investigation"
exclude :test_array_hash, "needs investigation"
exclude :test_array_length, "needs investigation"
exclude :test_array_max, "needs investigation"
exclude :test_array_min, "needs investigation"
exclude :test_array_minus, "needs investigation"
exclude :test_array_plus, "needs investigation"
exclude :test_block_parameter_should_not_create_objects, "NoMethodError: undefined method `count_objects' for module ObjectSpace"
exclude :test_c_func_with_sp_offset_under_tailcall, "NameError: uninitialized constant TestRubyOptimization::RubyVM"
exclude :test_callinfo_unreachable_path, "NameError: uninitialized constant RubyVM"
exclude :test_clear_unreachable_keyword_args, "NameError: uninitialized constant RubyVM"
exclude :test_eqq, "assert_separately failed with error message"
exclude :test_fixnum_and, "| <internal:core> core/io.rb:1360:in `ensure_open_and_writable': undefined method `&' for an instance of Integer (NoMethodError)"
exclude :test_fixnum_gt, "assert_separately failed with error message"
exclude :test_fixnum_lt, "very slow: 600.25s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_fixnum_minus, "very slow: 600.20s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_fixnum_plus, "assert_separately failed with error message"
exclude :test_hash_aref_with, "assert_separately failed with error message"
exclude :test_hash_aset_with, "needs investigation"
exclude :test_hash_empty?, "needs investigation"
exclude :test_hash_length, "needs investigation"
exclude :test_objtostring, "assert_separately failed with error message"
exclude :test_opt_case_dispatch, "NameError: uninitialized constant TestRubyOptimization::RubyVM"
exclude :test_opt_duparray_send_include_p, "NameError: uninitialized constant TestRubyOptimization::RubyVM"
exclude :test_opt_newarray_send_include_p, "NameError: uninitialized constant TestRubyOptimization::RubyVM"
exclude :test_optimized_rescue, "| truffleruby: No such file or directory --  (LoadError)"
exclude :test_peephole_array_freeze, "NameError: uninitialized constant TestRubyOptimization::RubyVM"
exclude :test_peephole_array_freeze_empty, "NameError: uninitialized constant TestRubyOptimization::RubyVM"
exclude :test_peephole_dstr, "NameError: uninitialized constant TestRubyOptimization::RubyVM"
exclude :test_peephole_hash_freeze, "NameError: uninitialized constant TestRubyOptimization::RubyVM"
exclude :test_peephole_hash_freeze_empty, "NameError: uninitialized constant TestRubyOptimization::RubyVM"
exclude :test_peephole_optimization_without_trace, "NameError: uninitialized constant RubyVM"
exclude :test_peephole_string_literal_range, "NameError: uninitialized constant TestRubyOptimization::RubyVM"
exclude :test_string_empty?, "needs investigation"
exclude :test_string_eq_neq, "needs investigation"
exclude :test_string_format, "needs investigation"
exclude :test_string_freeze, "Expected \"foo\" to be nil."
exclude :test_string_freeze_block, "<true> expected but was <\"block\">."
exclude :test_string_freeze_saves_memory, "IO buffer NOT resized prematurely because will likely be reused."
exclude :test_string_length, "needs investigation"
exclude :test_string_ltlt, "assert_separately failed with error message"
exclude :test_string_plus, "NoMethodError: undefined method `unpack1' for nil"
exclude :test_string_size, "needs investigation"
exclude :test_string_succ, "needs investigation"
exclude :test_string_uminus, "Expected \"foo\" to be nil."
exclude :test_tailcall, "NameError: uninitialized constant TestRubyOptimization::RubyVM"
exclude :test_tailcall_and_post_arg, "NameError: uninitialized constant TestRubyOptimization::RubyVM"
exclude :test_tailcall_condition_block, "NameError: uninitialized constant TestRubyOptimization::RubyVM"
exclude :test_tailcall_inhibited_by_block, "NameError: uninitialized constant TestRubyOptimization::RubyVM"
exclude :test_tailcall_inhibited_by_rescue, "NameError: uninitialized constant TestRubyOptimization::RubyVM"
exclude :test_tailcall_not_to_grow_stack, "NameError: uninitialized constant TestRubyOptimization::RubyVM"
exclude :test_tailcall_symbol_block_arg, "NameError: uninitialized constant TestRubyOptimization::RubyVM"
exclude :test_tailcall_with_block, "NameError: uninitialized constant TestRubyOptimization::RubyVM"
exclude :test_trace_optimized_methods, "ArgumentError: unknown event: c_call"
