exclude :test_ifunc_frame, "| ERROR: truffleruby: invalid option --parser=parse.y  (Use --help for usage instructions.)"
exclude :test_matches_backtrace_locations_main_thread, "undefined symbol: rb_profile_frames"
exclude :test_profile_frames, "undefined symbol: rb_profile_frames"
exclude :test_profile_thread_frames, "undefined symbol: rb_profile_thread_frames"
exclude :test_start, "undefined symbol: rb_profile_frames"
