exclude :test_argument_forwarding, "/b/b/e/main/test/mri/tests/ruby/test_syntax.rb:2002:in `test_argument_forwarding'."
exclude :test_array_kwsplat_hash, "<[]> expected but was <[{}]>."
exclude :test_class_module_Object_ancestors, "TypeError: an instance of Integer is not a class"
exclude :test_constant_reassignment_nested, "very slow: 85.74s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_constant_reassignment_toplevel, "very slow: 84.30s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_duplicated_rest_opt, "/b/b/e/main/test/mri/tests/ruby/test_syntax.rb:651:in `test_duplicated_rest_opt'."
exclude :test_error_message_encoding, "```# -*- coding: utf-8 -*-\ndef n \"∈\"; end\n```"
exclude :test_eval_return_toplevel, "NameError: uninitialized constant TestSyntax::Tempfile"
exclude :test_hash_kwsplat_hash, "<false> expected but was <true>."
exclude :test_heredoc_no_terminator, "/b/b/e/main/test/mri/tests/ruby/test_syntax.rb:1165:in `test_heredoc_no_terminator'."
exclude :test_invalid_jump, "| truffleruby: -e:1: Invalid redo (SyntaxError)"
exclude :test_it, "/b/b/e/main/test/mri/tests/ruby/test_syntax.rb:1902:in `test_it'."
exclude :test_keyword_self_reference, "/b/b/e/main/test/mri/tests/ruby/test_syntax.rb:410:in `test_keyword_self_reference'."
exclude :test_method_call_location, "<1743> expected but was <1740>."
exclude :test_methoddef_endless_command, "/b/b/e/main/test/mri/tests/ruby/test_syntax.rb:1801:in `test_methoddef_endless_command'."
exclude :test_no_label_with_percent, "/b/b/e/main/test/mri/tests/ruby/test_syntax.rb:578:in `test_no_label_with_percent'."
exclude :test_numbered_parameter, "Expected Exception(NameError) was raised, but the message doesn't match. Expected /undefined local variable or method '_1'/ to match \"undefined local variable or method `_1' for an instance of TestSyntax\"."
exclude :test_optional_self_reference, "/b/b/e/main/test/mri/tests/ruby/test_syntax.rb:476:in `test_optional_self_reference'."
exclude :test_return_in_BEGIN_in_eval, "Exception raised: <#<LocalJumpError: unexpected return>>"
exclude :test_return_toplevel, "very slow: 295.12s on truffleruby 24.2.0-dev-b555f590, like ruby 3.2.4, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 3700X 8-Core Processor (16 vCPUs)"
exclude :test_return_toplevel_with_argument, "LocalJumpError: unexpected return"
exclude :test_script_lines, "<[\"/tmp/bug4361_20251201-3984891-2isi21\"]> expected but was <[]>."
exclude :test_script_lines_encoding, "needs investigation"
exclude :test_syntax_error_at_newline, "/b/b/e/main/test/mri/tests/ruby/test_syntax.rb:1622:in `test_syntax_error_at_newline'."
