exclude :test_inspect, "<\"#<Enumerator::Lazy: 1..10>\"> expected but was <\"#<Enumerator::Lazy: #<Enumerator::Generator:"
exclude :test_laziness_conservation, "ArgumentError: wrong number of arguments (given 1, expected 0)"
exclude :test_lazy_to_enum_lazy_methods, "<[nil, 4]> expected but was <[nil]>."
exclude :test_with_index, "<[0, 1]> expected but was <[[[-1, 2], [0, 3]], [[-1, 2], [0, 3]]]>."
exclude :test_zip_nested, "<[[1, \"a\", \"a\"],"
