exclude :test_initialize_connect_timeout, "transient"
exclude :test_initialize_failure, "NameError: uninitialized constant Socket::ResolutionError"
exclude :test_initialize_fast_fallback_is_false, "hangs"
exclude :test_initialize_resolv_timeout, "NoMethodError: undefined method `close' for nil"
exclude :test_initialize_resolv_timeout_with_connection_failure, "[Errno::ETIMEDOUT] exception expected, not #<ArgumentError: unknown keywords: :resolv_timeout, :fast_fallback, :test_mode_settings>."
exclude :test_initialize_v4_hostname_resolved_earlier, "hangs"
exclude :test_initialize_v6_hostname_resolution_failed_and_v4_hostname_resolution_is_success, "hangs"
exclude :test_initialize_v6_hostname_resolved_earlier, "hangs"
exclude :test_initialize_v6_hostname_resolved_earlier_and_v6_server_is_not_listening, "hangs"
exclude :test_initialize_v6_hostname_resolved_in_resolution_delay, "hangs"
exclude :test_initialize_v6_hostname_resolved_later_and_v6_server_is_not_listening, "hangs"
exclude :test_initialize_with_connection_failure_after_hostname_resolution_failure, "[Errno::ECONNREFUSED] exception expected, not #<ArgumentError: unknown keywords: :fast_fallback, :test_mode_settings>."
exclude :test_initialize_with_hostname_resolution_failure_after_connection_failure, "[Errno::ECONNREFUSED] exception expected, not #<ArgumentError: unknown keywords: :fast_fallback, :test_mode_settings>."
exclude :test_inspect, "Expected /AF_INET/ to match \"#<TCPServer:fd 39>\"."
exclude :test_recvfrom, "SocketError: need IPv4 or IPv6 address"
