exclude :test_accept_loop, "NameError: undefined local variable or method `tcp_fast_fallback' for class Socket"
exclude :test_accept_loop_multi_port, "NameError: undefined local variable or method `tcp_fast_fallback' for class Socket"
exclude :test_bind, "Expected /bind\\(2\\)\\ for\\ 127\\.0\\.0\\.1:36337/ to match \"Address already in use - bind(2)\"."
exclude :test_closed_read, "retain-on-retag; test timed out"
exclude :test_connect_timeout, "NameError: undefined local variable or method `tcp_fast_fallback' for class Socket"
exclude :test_getaddrinfo, "NameError: uninitialized constant Socket::ResolutionError"
exclude :test_getaddrinfo_raises_no_errors_on_port_argument_of_0, "NameError: uninitialized constant Socket::ResolutionError"
exclude :test_getnameinfo, "NameError: uninitialized constant Socket::ResolutionError"
exclude :test_resolurion_error_error_code, "NoMethodError: undefined method `error_code' for an instance of SocketError"
exclude :test_socket_new_cloexec, "Failed assertion, no message given."
exclude :test_tcp_cloexec, "Failed assertion, no message given."
exclude :test_tcp_fast_fallback, "NoMethodError: undefined method `tcp_fast_fallback' for class Socket"
exclude :test_tcp_socket_all_hostname_resolution_failed, "Exception(SocketError) with message matches to \"Last hostname resolution error\"."
exclude :test_tcp_socket_hostname_resolution_failed_after_connection_failure, "[Errno::ECONNREFUSED, SystemCallError] exception expected, not #<NameError: undefined local variable or method `tcp_fast_fallback' for class Socket>."
exclude :test_tcp_socket_one_hostname_resolution_succeeded_at_least, "Expected [[550249, #<Process::Status: pid 550249 exit nil>]] to be empty."
exclude :test_tcp_socket_resolv_timeout, "[Errno::ETIMEDOUT] exception expected, not #<NameError: undefined local variable or method `tcp_fast_fallback' for class Socket>."
exclude :test_tcp_socket_resolv_timeout_with_connection_failure, "[Errno::ETIMEDOUT] exception expected, not #<NameError: undefined local variable or method `tcp_fast_fallback' for class Socket>."
exclude :test_tcp_socket_v4_hostname_resolved_earlier, "hangs"
exclude :test_tcp_socket_v6_address_passed, "hangs"
exclude :test_tcp_socket_v6_hostname_resolved_earlier, "hangs"
exclude :test_tcp_socket_v6_hostname_resolved_earlier_and_v6_server_is_not_listening, "hangs"
exclude :test_tcp_socket_v6_hostname_resolved_in_resolution_delay, "hangs"
exclude :test_timestamp, "NoMethodError: undefined method `cmsg_is?' for nil"
exclude :test_timestampns, "NoMethodError: undefined method `cmsg_is?' for nil"
exclude :test_udp_server, "spurious; failed in CI with `RuntimeError: thread killed`"
exclude :test_unix, "Failed assertion, no message given."
