exclude :test_beg_len, "TypeError: no implicit conversion of Object into Integer"
exclude :test_comparison_when_recursive, "SystemStackError: stack level too deep"
exclude :test_count, "<6> expected but was <5>."
exclude :test_cover, "Expected 1..5 to not be cover? 3..2."
exclude :test_cyclic_range_inspect, "SystemStackError: stack level too deep"
exclude :test_duckrange, "TypeError: no implicit conversion of TestRange::DuckRange into Integer"
exclude :test_each, "NoMethodError: undefined method `<' for nil"
exclude :test_each_with_succ, "NoMethodError: undefined method `i' for nil"
exclude :test_eqq, "Expected 0..10 to not be === 0..10."
exclude :test_frozen_initialize, "FrozenError expected but nothing was raised."
exclude :test_include, "hangs"
exclude :test_initialize_twice, "[FrozenError] exception expected, not #<NameError: `initialize' called twice>."
exclude :test_last_with_redefine_each, "needs investigation"
exclude :test_max, "ArgumentError: wrong number of arguments (given 1, expected 0)"
exclude :test_min, "ArgumentError: wrong number of arguments (given 1, expected 0)"
exclude :test_overlap?, "Expected 1.. to not be overlap? \"a\".."
exclude :test_range_bsearch_for_floats, "needs investigation"
exclude :test_range_numeric_string, "<[\"9\", \"10\"]> expected but was <[]>."
exclude :test_reverse_each_size, "TypeError expected but nothing was raised."
exclude :test_size, "failed on 1...5.5."
exclude :test_step_non_numeric_range, "ArgumentError: invalid value for Integer(): a"
exclude :test_step_numeric_fixnum_boundary, "ArgumentError expected but nothing was raised."
exclude :test_step_numeric_range, "[ArgumentError] exception expected, not #<TypeError: can't iterate from NilClass>."
exclude :test_step_string_legacy, "[ArgumentError] exception expected, not #<TypeError: can't iterate from NilClass>."
exclude :test_step_symbol_legacy, "[ArgumentError] exception expected, not #<TypeError: can't iterate from NilClass>."
exclude :test_step_with_nonnumeric_endpoint, "TypeError: can't iterate from #<Class:0x1dba8>"
