exclude :test_backtrace_in_eval, "| (eval):1:in '<main>': unhandled exception"
exclude :test_cause_at_end, "| "
exclude :test_cause_thread_with_cause, "NoMethodError: undefined method 'message' for nil"
exclude :test_errat, "| <internal:core> core/exception.rb:67:in 'Exception#set_backtrace': backtrace must be Array of String (TypeError)"
exclude :test_errinfo_encoding_in_debug, "Expected \"\" to include \"#<Module:0x628>::Cエラー\"."
exclude :test_errinfo_in_debug, "needs investigation"
exclude :test_errno_constants, "<[:NOERROR]> expected but was <[:DomainError]>."
exclude :test_exception_in_ensure_with_next, "NameError: uninitialized constant TestException::RubyVM"
exclude :test_inspect, "<\"#<Class:0x7f8>\"> expected but was <nil>."
exclude :test_machine_stackoverflow, "assert_separately failed with error message"
exclude :test_machine_stackoverflow_by_define_method, "assert_separately failed with error message"
exclude :test_marshal_circular_cause, "\"\\u0004\\bo:\\u0011RuntimeError\\b:\\tmesgI\\\"\\berr\\u0006:\\u0006ET:\\abt[\\u0000:\\ncause@\\u0005\"."
exclude :test_output_string_encoding, "<1> expected but was <0>."
exclude :test_set_backtrace, "Expected \"backtrace must be Array of String\" to include \"backtrace must be an Array of String or an Array of Thread::Backtrace::Location\"."
exclude :test_stackoverflow, "slow; it overflows the stack, as expected"
exclude :test_too_many_args_in_eval, "[SystemStackError] exception expected, not #<ArgumentError: wrong number of arguments (given 140000, expected 0..3)>."
exclude :test_undef_Warning_warn, "[NoMethodError] exception expected, not #<NameError: undefined method 'warn' for class 'Module'>."
exclude :test_undefined_backtrace, "assert_separately failed with error message"
exclude :test_warn_deprecated_backwards_compatibility_category, "<:deprecated> expected but was <nil>."
exclude :test_warning_category, "categories."
exclude :test_warning_warn_circular_require_backtrace, "Expected /^\\tfrom \\/tmp\\/circular20260115\\-166199\\-yqifk4\\.rb:1:/ to match \"/tmp/circular20260115-166199-yqifk4.rb:1: warning: loading in progress, circular require considered harmful - /tmp/circular20260115-166199-yqifk4.rb\\n\"."
exclude :test_wrong_backtrace, "assert_separately failed with error message"
