exclude :test_append_bytes_into_binary, "NoMethodError: undefined method `append_as_bytes' for an instance of TestString::S2"
exclude :test_append_bytes_into_utf32, "NoMethodError: undefined method `append_as_bytes' for an instance of TestString::S2"
exclude :test_append_bytes_into_utf8, "NoMethodError: undefined method `append_as_bytes' for an instance of TestString::S2"
exclude :test_ascii_incomat_inspect, "transient GR-34182"
exclude :test_byterindex, "Expected #<MatchData \"byterindex with string does not affect $~\"> to be nil."
exclude :test_byteslice_grapheme_clusters, "ArgumentError: invalid byte sequence in UTF-8"
exclude :test_chilled_string, "<\"chilled\">"
exclude :test_chomp!, "transient GR-34182"
exclude :test_crypt, "transient GR-34182"
exclude :test_dummy_inspect, "transient GR-34182"
exclude :test_dump, "transient GR-34182"
exclude :test_each, "transient GR-34182"
exclude :test_each_grapheme_cluster, "transient GR-34182"
exclude :test_each_line, "transient GR-34182"
exclude :test_each_line_chomp, "transient GR-34182"
exclude :test_fs, "transient GR-34182"
exclude :test_grapheme_clusters_memory_leak, "[Bug #todo]"
exclude :test_hash, "<0> expected to be != to"
exclude :test_initialize, "transient GR-34182"
exclude :test_inspect_next_line, "<\"\\\"\\\\u0085\\\"\"> expected but was <\"\\\"\u0085\\\"\">."
exclude :test_match_method, "transient GR-34182"
exclude :test_partition, "transient GR-34182"
exclude :test_respond_to, "transient GR-34182"
exclude :test_rindex, "Expected #<MatchData \"rindex with string does not affect $~\"> to be nil."
exclude :test_rstrip, "transient GR-34182"
exclude :test_rstrip_bang, "transient GR-34182"
exclude :test_setter, "transient GR-34182"
exclude :test_split_with_block, "RuntimeError expected but nothing was raised."
exclude :test_start_with?, "Expected \"Ä\".start_with?(\"\\xC3\") to return false."
exclude :test_start_with_timeout_memory_leak, "| ERROR: truffleruby: invalid option --parser=parse.y  (Use --help for usage instructions.)"
exclude :test_string_interpolations_across_heaps_get_embedded, "NameError: uninitialized constant GC::INTERNAL_CONSTANTS"
exclude :test_to_i, "transient GR-34182"
exclude :test_tr, "<\"XYC\"> expected but was <\"YYC\">."
exclude :test_tr!, "<\"XYC\"> expected but was <\"YYC\">."
exclude :test_tr_s, "<\"XYC\"> expected but was <\"YC\">."
exclude :test_tr_s!, "<\"XYC\"> expected but was <\"YC\">."
exclude :test_uminus_no_freeze_not_bare, "Expected \"foo\" to be an instance of TestString::S2, not String."
exclude :test_undump, "transient GR-34182"
exclude :test_upto_nonalnum, "transient GR-34182"
exclude :test_upto_numeric, "transient GR-34182"
