exclude :test_birthtime, "NoMethodError: undefined method `birthtime' for an instance of Pathname"
exclude :test_each_entry_enumerator, "LocalJumpError: no block given (yield)"
exclude :test_find, "LocalJumpError: no block given (yield)"
exclude :test_mkpath, "<#<Pathname:a/b/c/d>> expected but was <nil>."
exclude :test_mktmpdir, "NoMethodError: undefined method `mktmpdir' for class Pathname"
exclude :test_relative_path_from_mock, "TypeError: no implicit conversion of Object into String"
exclude :test_rmtree, "<#<Pathname:a>> expected but was <nil>."
exclude :test_s_glob_3args, "<[#<Pathname:.>, #<Pathname:f>]> expected but was <[#<Pathname:.>, #<Pathname:..>, #<Pathname:f>]>."
exclude :test_split, "[TypeError] exception expected, not #<NoMethodError: undefined method `map' for nil>."
exclude :test_world_readable?, "NoMethodError: undefined method `world_readable?' for module FileTest"
exclude :test_world_writable?, "NoMethodError: undefined method `world_writable?' for module FileTest"
