exclude :test_gc_auto_compact_get_not_implemented, "NotImplementedError expected but nothing was raised."
exclude :test_gc_auto_compact_set_not_implemented, "NotImplementedError expected but nothing was raised."
exclude :test_gc_compact_not_implemented, "[NotImplementedError] exception expected, not #<NoMethodError: undefined method `compact' for module GC>."
exclude :test_gc_latest_compact_info_not_implemented, "[NotImplementedError] exception expected, not #<NoMethodError: undefined method `latest_compact_info' for module GC>."
exclude :test_gc_verify_compaction_references_not_implemented, "[NotImplementedError] exception expected, not #<NoMethodError: undefined method `verify_compaction_references' for module GC>."
