/*
 * Copyright (c) 2026 TruffleRuby contributors
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions are met:
 *
 * 1. Redistributions of source code must retain the above copyright notice, this
 *    list of conditions and the following disclaimer.
 *
 * 2. Redistributions in binary form must reproduce the above copyright notice,
 *    this list of conditions and the following disclaimer in the documentation
 *    and/or other materials provided with the distribution.
 *
 * 3. Neither the name of the copyright holder nor the names of its
 *    contributors may be used to endorse or promote products derived from
 *    this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
 * AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
 * IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
 * DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
 * FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
 * DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
 * SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
 * OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
 * OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
 */
package org.truffleruby.cext;

// GENERATED BY tool/generate-cext-upcalls.rb - DO NOT EDIT

import java.lang.invoke.MethodHandle;

import com.oracle.truffle.api.CompilerDirectives;
import com.oracle.truffle.api.CompilerDirectives.TruffleBoundary;
import com.oracle.truffle.api.dsl.Cached;
import com.oracle.truffle.api.dsl.Specialization;
import com.oracle.truffle.api.profiles.InlinedBranchProfile;

import org.truffleruby.annotations.CoreModule;
import org.truffleruby.annotations.Primitive;
import org.truffleruby.builtins.PrimitiveArrayArgumentsNode;
import org.truffleruby.core.fiber.RubyFiber;
import org.truffleruby.platform.FFMSupport;

// @formatter:off
/** The Primitive.cext_invoke_<signature> primitives calling native functions for the C extension support: the
 * rb_tr_setjmp_wrapper_* functions and the native helper functions of libtruffleruby. The first argument is the address
 * of the native function to call, the following ones its arguments (VALUE handles, pointers and integers, coerced by
 * {@link CExtDowncallArgumentNode}).
 *
 * <p>
 * After the native call returns, the pending C extension exception (captured at an FFM upcall boundary while the native
 * code was running, see {@link CExtFFMLayer#reportException}) is rethrown, replacing the Truffle NFI
 * exceptionCheck mechanism. */
@CoreModule("Truffle::CExtInvoke")
public abstract class CExtInvokePrimitives {

    public abstract static class CExtInvokeNode extends PrimitiveArrayArgumentsNode {
        protected final void checkPendingException(InlinedBranchProfile exceptionProfile) {
            final RubyFiber fiber = getLanguage().getCurrentFiber();
            if (fiber.pendingCExtException != null) {
                exceptionProfile.enter(this);
                CExtFFMLayer.checkPendingException(getContext(), fiber);
            }
        }
    }

    private static final MethodHandle HANDLE_L_L = FFMSupport.createDowncallHandle("L(L)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static long invokeL_L(long function, long a0) {
        try {
            return (long) HANDLE_L_L.invokeExact(function, a0);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_l_l")
    public abstract static class InvokeL_LNode extends CExtInvokeNode {
        @Specialization
        long invoke(long function, Object a0,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            final long result = invokeL_L(function, arg0Node.execute(a0));
            checkPendingException(exceptionProfile);
            return result;
        }
    }

    private static final MethodHandle HANDLE_L_LL = FFMSupport.createDowncallHandle("L(LL)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static long invokeL_LL(long function, long a0, long a1) {
        try {
            return (long) HANDLE_L_LL.invokeExact(function, a0, a1);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_l_ll")
    public abstract static class InvokeL_LLNode extends CExtInvokeNode {
        @Specialization
        long invoke(long function, Object a0, Object a1,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached CExtDowncallArgumentNode arg1Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            final long result = invokeL_LL(function, arg0Node.execute(a0), arg1Node.execute(a1));
            checkPendingException(exceptionProfile);
            return result;
        }
    }

    private static final MethodHandle HANDLE_L_LLL = FFMSupport.createDowncallHandle("L(LLL)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static long invokeL_LLL(long function, long a0, long a1, long a2) {
        try {
            return (long) HANDLE_L_LLL.invokeExact(function, a0, a1, a2);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_l_lll")
    public abstract static class InvokeL_LLLNode extends CExtInvokeNode {
        @Specialization
        long invoke(long function, Object a0, Object a1, Object a2,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached CExtDowncallArgumentNode arg1Node,
                @Cached CExtDowncallArgumentNode arg2Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            final long result = invokeL_LLL(function, arg0Node.execute(a0), arg1Node.execute(a1), arg2Node.execute(a2));
            checkPendingException(exceptionProfile);
            return result;
        }
    }

    private static final MethodHandle HANDLE_L_LLLL = FFMSupport.createDowncallHandle("L(LLLL)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static long invokeL_LLLL(long function, long a0, long a1, long a2, long a3) {
        try {
            return (long) HANDLE_L_LLLL.invokeExact(function, a0, a1, a2, a3);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_l_llll")
    public abstract static class InvokeL_LLLLNode extends CExtInvokeNode {
        @Specialization
        long invoke(long function, Object a0, Object a1, Object a2, Object a3,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached CExtDowncallArgumentNode arg1Node,
                @Cached CExtDowncallArgumentNode arg2Node,
                @Cached CExtDowncallArgumentNode arg3Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            final long result = invokeL_LLLL(function, arg0Node.execute(a0), arg1Node.execute(a1), arg2Node.execute(a2), arg3Node.execute(a3));
            checkPendingException(exceptionProfile);
            return result;
        }
    }

    private static final MethodHandle HANDLE_L_LLLLL = FFMSupport.createDowncallHandle("L(LLLLL)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static long invokeL_LLLLL(long function, long a0, long a1, long a2, long a3, long a4) {
        try {
            return (long) HANDLE_L_LLLLL.invokeExact(function, a0, a1, a2, a3, a4);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_l_lllll")
    public abstract static class InvokeL_LLLLLNode extends CExtInvokeNode {
        @Specialization
        long invoke(long function, Object a0, Object a1, Object a2, Object a3, Object a4,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached CExtDowncallArgumentNode arg1Node,
                @Cached CExtDowncallArgumentNode arg2Node,
                @Cached CExtDowncallArgumentNode arg3Node,
                @Cached CExtDowncallArgumentNode arg4Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            final long result = invokeL_LLLLL(function, arg0Node.execute(a0), arg1Node.execute(a1), arg2Node.execute(a2), arg3Node.execute(a3), arg4Node.execute(a4));
            checkPendingException(exceptionProfile);
            return result;
        }
    }

    private static final MethodHandle HANDLE_L_LLLLLL = FFMSupport.createDowncallHandle("L(LLLLLL)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static long invokeL_LLLLLL(long function, long a0, long a1, long a2, long a3, long a4, long a5) {
        try {
            return (long) HANDLE_L_LLLLLL.invokeExact(function, a0, a1, a2, a3, a4, a5);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_l_llllll")
    public abstract static class InvokeL_LLLLLLNode extends CExtInvokeNode {
        @Specialization
        long invoke(long function, Object a0, Object a1, Object a2, Object a3, Object a4, Object a5,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached CExtDowncallArgumentNode arg1Node,
                @Cached CExtDowncallArgumentNode arg2Node,
                @Cached CExtDowncallArgumentNode arg3Node,
                @Cached CExtDowncallArgumentNode arg4Node,
                @Cached CExtDowncallArgumentNode arg5Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            final long result = invokeL_LLLLLL(function, arg0Node.execute(a0), arg1Node.execute(a1), arg2Node.execute(a2), arg3Node.execute(a3), arg4Node.execute(a4), arg5Node.execute(a5));
            checkPendingException(exceptionProfile);
            return result;
        }
    }

    private static final MethodHandle HANDLE_L_LLLLLLL = FFMSupport.createDowncallHandle("L(LLLLLLL)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static long invokeL_LLLLLLL(long function, long a0, long a1, long a2, long a3, long a4, long a5, long a6) {
        try {
            return (long) HANDLE_L_LLLLLLL.invokeExact(function, a0, a1, a2, a3, a4, a5, a6);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_l_lllllll")
    public abstract static class InvokeL_LLLLLLLNode extends CExtInvokeNode {
        @Specialization
        long invoke(long function, Object a0, Object a1, Object a2, Object a3, Object a4, Object a5, Object a6,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached CExtDowncallArgumentNode arg1Node,
                @Cached CExtDowncallArgumentNode arg2Node,
                @Cached CExtDowncallArgumentNode arg3Node,
                @Cached CExtDowncallArgumentNode arg4Node,
                @Cached CExtDowncallArgumentNode arg5Node,
                @Cached CExtDowncallArgumentNode arg6Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            final long result = invokeL_LLLLLLL(function, arg0Node.execute(a0), arg1Node.execute(a1), arg2Node.execute(a2), arg3Node.execute(a3), arg4Node.execute(a4), arg5Node.execute(a5), arg6Node.execute(a6));
            checkPendingException(exceptionProfile);
            return result;
        }
    }

    private static final MethodHandle HANDLE_L_LLLLLLLL = FFMSupport.createDowncallHandle("L(LLLLLLLL)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static long invokeL_LLLLLLLL(long function, long a0, long a1, long a2, long a3, long a4, long a5, long a6, long a7) {
        try {
            return (long) HANDLE_L_LLLLLLLL.invokeExact(function, a0, a1, a2, a3, a4, a5, a6, a7);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_l_llllllll")
    public abstract static class InvokeL_LLLLLLLLNode extends CExtInvokeNode {
        @Specialization
        long invoke(long function, Object a0, Object a1, Object a2, Object a3, Object a4, Object a5, Object a6, Object a7,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached CExtDowncallArgumentNode arg1Node,
                @Cached CExtDowncallArgumentNode arg2Node,
                @Cached CExtDowncallArgumentNode arg3Node,
                @Cached CExtDowncallArgumentNode arg4Node,
                @Cached CExtDowncallArgumentNode arg5Node,
                @Cached CExtDowncallArgumentNode arg6Node,
                @Cached CExtDowncallArgumentNode arg7Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            final long result = invokeL_LLLLLLLL(function, arg0Node.execute(a0), arg1Node.execute(a1), arg2Node.execute(a2), arg3Node.execute(a3), arg4Node.execute(a4), arg5Node.execute(a5), arg6Node.execute(a6), arg7Node.execute(a7));
            checkPendingException(exceptionProfile);
            return result;
        }
    }

    private static final MethodHandle HANDLE_L_LLLLLLLLL = FFMSupport.createDowncallHandle("L(LLLLLLLLL)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static long invokeL_LLLLLLLLL(long function, long a0, long a1, long a2, long a3, long a4, long a5, long a6, long a7, long a8) {
        try {
            return (long) HANDLE_L_LLLLLLLLL.invokeExact(function, a0, a1, a2, a3, a4, a5, a6, a7, a8);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_l_lllllllll")
    public abstract static class InvokeL_LLLLLLLLLNode extends CExtInvokeNode {
        @Specialization
        long invoke(long function, Object a0, Object a1, Object a2, Object a3, Object a4, Object a5, Object a6, Object a7, Object a8,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached CExtDowncallArgumentNode arg1Node,
                @Cached CExtDowncallArgumentNode arg2Node,
                @Cached CExtDowncallArgumentNode arg3Node,
                @Cached CExtDowncallArgumentNode arg4Node,
                @Cached CExtDowncallArgumentNode arg5Node,
                @Cached CExtDowncallArgumentNode arg6Node,
                @Cached CExtDowncallArgumentNode arg7Node,
                @Cached CExtDowncallArgumentNode arg8Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            final long result = invokeL_LLLLLLLLL(function, arg0Node.execute(a0), arg1Node.execute(a1), arg2Node.execute(a2), arg3Node.execute(a3), arg4Node.execute(a4), arg5Node.execute(a5), arg6Node.execute(a6), arg7Node.execute(a7), arg8Node.execute(a8));
            checkPendingException(exceptionProfile);
            return result;
        }
    }

    private static final MethodHandle HANDLE_L_LLLLLLLLLL = FFMSupport.createDowncallHandle("L(LLLLLLLLLL)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static long invokeL_LLLLLLLLLL(long function, long a0, long a1, long a2, long a3, long a4, long a5, long a6, long a7, long a8, long a9) {
        try {
            return (long) HANDLE_L_LLLLLLLLLL.invokeExact(function, a0, a1, a2, a3, a4, a5, a6, a7, a8, a9);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_l_llllllllll")
    public abstract static class InvokeL_LLLLLLLLLLNode extends CExtInvokeNode {
        @Specialization
        long invoke(long function, Object a0, Object a1, Object a2, Object a3, Object a4, Object a5, Object a6, Object a7, Object a8, Object a9,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached CExtDowncallArgumentNode arg1Node,
                @Cached CExtDowncallArgumentNode arg2Node,
                @Cached CExtDowncallArgumentNode arg3Node,
                @Cached CExtDowncallArgumentNode arg4Node,
                @Cached CExtDowncallArgumentNode arg5Node,
                @Cached CExtDowncallArgumentNode arg6Node,
                @Cached CExtDowncallArgumentNode arg7Node,
                @Cached CExtDowncallArgumentNode arg8Node,
                @Cached CExtDowncallArgumentNode arg9Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            final long result = invokeL_LLLLLLLLLL(function, arg0Node.execute(a0), arg1Node.execute(a1), arg2Node.execute(a2), arg3Node.execute(a3), arg4Node.execute(a4), arg5Node.execute(a5), arg6Node.execute(a6), arg7Node.execute(a7), arg8Node.execute(a8), arg9Node.execute(a9));
            checkPendingException(exceptionProfile);
            return result;
        }
    }

    private static final MethodHandle HANDLE_L_LLLLLLLLLLL = FFMSupport.createDowncallHandle("L(LLLLLLLLLLL)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static long invokeL_LLLLLLLLLLL(long function, long a0, long a1, long a2, long a3, long a4, long a5, long a6, long a7, long a8, long a9, long a10) {
        try {
            return (long) HANDLE_L_LLLLLLLLLLL.invokeExact(function, a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_l_lllllllllll")
    public abstract static class InvokeL_LLLLLLLLLLLNode extends CExtInvokeNode {
        @Specialization
        long invoke(long function, Object a0, Object a1, Object a2, Object a3, Object a4, Object a5, Object a6, Object a7, Object a8, Object a9, Object a10,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached CExtDowncallArgumentNode arg1Node,
                @Cached CExtDowncallArgumentNode arg2Node,
                @Cached CExtDowncallArgumentNode arg3Node,
                @Cached CExtDowncallArgumentNode arg4Node,
                @Cached CExtDowncallArgumentNode arg5Node,
                @Cached CExtDowncallArgumentNode arg6Node,
                @Cached CExtDowncallArgumentNode arg7Node,
                @Cached CExtDowncallArgumentNode arg8Node,
                @Cached CExtDowncallArgumentNode arg9Node,
                @Cached CExtDowncallArgumentNode arg10Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            final long result = invokeL_LLLLLLLLLLL(function, arg0Node.execute(a0), arg1Node.execute(a1), arg2Node.execute(a2), arg3Node.execute(a3), arg4Node.execute(a4), arg5Node.execute(a5), arg6Node.execute(a6), arg7Node.execute(a7), arg8Node.execute(a8), arg9Node.execute(a9), arg10Node.execute(a10));
            checkPendingException(exceptionProfile);
            return result;
        }
    }

    private static final MethodHandle HANDLE_L_LLLLLLLLLLLL = FFMSupport.createDowncallHandle("L(LLLLLLLLLLLL)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static long invokeL_LLLLLLLLLLLL(long function, long a0, long a1, long a2, long a3, long a4, long a5, long a6, long a7, long a8, long a9, long a10, long a11) {
        try {
            return (long) HANDLE_L_LLLLLLLLLLLL.invokeExact(function, a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_l_llllllllllll")
    public abstract static class InvokeL_LLLLLLLLLLLLNode extends CExtInvokeNode {
        @Specialization
        long invoke(long function, Object a0, Object a1, Object a2, Object a3, Object a4, Object a5, Object a6, Object a7, Object a8, Object a9, Object a10, Object a11,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached CExtDowncallArgumentNode arg1Node,
                @Cached CExtDowncallArgumentNode arg2Node,
                @Cached CExtDowncallArgumentNode arg3Node,
                @Cached CExtDowncallArgumentNode arg4Node,
                @Cached CExtDowncallArgumentNode arg5Node,
                @Cached CExtDowncallArgumentNode arg6Node,
                @Cached CExtDowncallArgumentNode arg7Node,
                @Cached CExtDowncallArgumentNode arg8Node,
                @Cached CExtDowncallArgumentNode arg9Node,
                @Cached CExtDowncallArgumentNode arg10Node,
                @Cached CExtDowncallArgumentNode arg11Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            final long result = invokeL_LLLLLLLLLLLL(function, arg0Node.execute(a0), arg1Node.execute(a1), arg2Node.execute(a2), arg3Node.execute(a3), arg4Node.execute(a4), arg5Node.execute(a5), arg6Node.execute(a6), arg7Node.execute(a7), arg8Node.execute(a8), arg9Node.execute(a9), arg10Node.execute(a10), arg11Node.execute(a11));
            checkPendingException(exceptionProfile);
            return result;
        }
    }

    private static final MethodHandle HANDLE_L_LLLLLLLLLLLLL = FFMSupport.createDowncallHandle("L(LLLLLLLLLLLLL)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static long invokeL_LLLLLLLLLLLLL(long function, long a0, long a1, long a2, long a3, long a4, long a5, long a6, long a7, long a8, long a9, long a10, long a11, long a12) {
        try {
            return (long) HANDLE_L_LLLLLLLLLLLLL.invokeExact(function, a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_l_lllllllllllll")
    public abstract static class InvokeL_LLLLLLLLLLLLLNode extends CExtInvokeNode {
        @Specialization
        long invoke(long function, Object a0, Object a1, Object a2, Object a3, Object a4, Object a5, Object a6, Object a7, Object a8, Object a9, Object a10, Object a11, Object a12,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached CExtDowncallArgumentNode arg1Node,
                @Cached CExtDowncallArgumentNode arg2Node,
                @Cached CExtDowncallArgumentNode arg3Node,
                @Cached CExtDowncallArgumentNode arg4Node,
                @Cached CExtDowncallArgumentNode arg5Node,
                @Cached CExtDowncallArgumentNode arg6Node,
                @Cached CExtDowncallArgumentNode arg7Node,
                @Cached CExtDowncallArgumentNode arg8Node,
                @Cached CExtDowncallArgumentNode arg9Node,
                @Cached CExtDowncallArgumentNode arg10Node,
                @Cached CExtDowncallArgumentNode arg11Node,
                @Cached CExtDowncallArgumentNode arg12Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            final long result = invokeL_LLLLLLLLLLLLL(function, arg0Node.execute(a0), arg1Node.execute(a1), arg2Node.execute(a2), arg3Node.execute(a3), arg4Node.execute(a4), arg5Node.execute(a5), arg6Node.execute(a6), arg7Node.execute(a7), arg8Node.execute(a8), arg9Node.execute(a9), arg10Node.execute(a10), arg11Node.execute(a11), arg12Node.execute(a12));
            checkPendingException(exceptionProfile);
            return result;
        }
    }

    private static final MethodHandle HANDLE_L_LLLLLLLLLLLLLL = FFMSupport.createDowncallHandle("L(LLLLLLLLLLLLLL)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static long invokeL_LLLLLLLLLLLLLL(long function, long a0, long a1, long a2, long a3, long a4, long a5, long a6, long a7, long a8, long a9, long a10, long a11, long a12, long a13) {
        try {
            return (long) HANDLE_L_LLLLLLLLLLLLLL.invokeExact(function, a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_l_llllllllllllll")
    public abstract static class InvokeL_LLLLLLLLLLLLLLNode extends CExtInvokeNode {
        @Specialization
        long invoke(long function, Object a0, Object a1, Object a2, Object a3, Object a4, Object a5, Object a6, Object a7, Object a8, Object a9, Object a10, Object a11, Object a12, Object a13,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached CExtDowncallArgumentNode arg1Node,
                @Cached CExtDowncallArgumentNode arg2Node,
                @Cached CExtDowncallArgumentNode arg3Node,
                @Cached CExtDowncallArgumentNode arg4Node,
                @Cached CExtDowncallArgumentNode arg5Node,
                @Cached CExtDowncallArgumentNode arg6Node,
                @Cached CExtDowncallArgumentNode arg7Node,
                @Cached CExtDowncallArgumentNode arg8Node,
                @Cached CExtDowncallArgumentNode arg9Node,
                @Cached CExtDowncallArgumentNode arg10Node,
                @Cached CExtDowncallArgumentNode arg11Node,
                @Cached CExtDowncallArgumentNode arg12Node,
                @Cached CExtDowncallArgumentNode arg13Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            final long result = invokeL_LLLLLLLLLLLLLL(function, arg0Node.execute(a0), arg1Node.execute(a1), arg2Node.execute(a2), arg3Node.execute(a3), arg4Node.execute(a4), arg5Node.execute(a5), arg6Node.execute(a6), arg7Node.execute(a7), arg8Node.execute(a8), arg9Node.execute(a9), arg10Node.execute(a10), arg11Node.execute(a11), arg12Node.execute(a12), arg13Node.execute(a13));
            checkPendingException(exceptionProfile);
            return result;
        }
    }

    private static final MethodHandle HANDLE_L_LLLLLLLLLLLLLLL = FFMSupport.createDowncallHandle("L(LLLLLLLLLLLLLLL)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static long invokeL_LLLLLLLLLLLLLLL(long function, long a0, long a1, long a2, long a3, long a4, long a5, long a6, long a7, long a8, long a9, long a10, long a11, long a12, long a13, long a14) {
        try {
            return (long) HANDLE_L_LLLLLLLLLLLLLLL.invokeExact(function, a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_l_lllllllllllllll")
    public abstract static class InvokeL_LLLLLLLLLLLLLLLNode extends CExtInvokeNode {
        @Specialization
        long invoke(long function, Object a0, Object a1, Object a2, Object a3, Object a4, Object a5, Object a6, Object a7, Object a8, Object a9, Object a10, Object a11, Object a12, Object a13, Object a14,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached CExtDowncallArgumentNode arg1Node,
                @Cached CExtDowncallArgumentNode arg2Node,
                @Cached CExtDowncallArgumentNode arg3Node,
                @Cached CExtDowncallArgumentNode arg4Node,
                @Cached CExtDowncallArgumentNode arg5Node,
                @Cached CExtDowncallArgumentNode arg6Node,
                @Cached CExtDowncallArgumentNode arg7Node,
                @Cached CExtDowncallArgumentNode arg8Node,
                @Cached CExtDowncallArgumentNode arg9Node,
                @Cached CExtDowncallArgumentNode arg10Node,
                @Cached CExtDowncallArgumentNode arg11Node,
                @Cached CExtDowncallArgumentNode arg12Node,
                @Cached CExtDowncallArgumentNode arg13Node,
                @Cached CExtDowncallArgumentNode arg14Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            final long result = invokeL_LLLLLLLLLLLLLLL(function, arg0Node.execute(a0), arg1Node.execute(a1), arg2Node.execute(a2), arg3Node.execute(a3), arg4Node.execute(a4), arg5Node.execute(a5), arg6Node.execute(a6), arg7Node.execute(a7), arg8Node.execute(a8), arg9Node.execute(a9), arg10Node.execute(a10), arg11Node.execute(a11), arg12Node.execute(a12), arg13Node.execute(a13), arg14Node.execute(a14));
            checkPendingException(exceptionProfile);
            return result;
        }
    }

    private static final MethodHandle HANDLE_L_LLLLLLLLLLLLLLLL = FFMSupport.createDowncallHandle("L(LLLLLLLLLLLLLLLL)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static long invokeL_LLLLLLLLLLLLLLLL(long function, long a0, long a1, long a2, long a3, long a4, long a5, long a6, long a7, long a8, long a9, long a10, long a11, long a12, long a13, long a14, long a15) {
        try {
            return (long) HANDLE_L_LLLLLLLLLLLLLLLL.invokeExact(function, a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_l_llllllllllllllll")
    public abstract static class InvokeL_LLLLLLLLLLLLLLLLNode extends CExtInvokeNode {
        @Specialization
        long invoke(long function, Object a0, Object a1, Object a2, Object a3, Object a4, Object a5, Object a6, Object a7, Object a8, Object a9, Object a10, Object a11, Object a12, Object a13, Object a14, Object a15,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached CExtDowncallArgumentNode arg1Node,
                @Cached CExtDowncallArgumentNode arg2Node,
                @Cached CExtDowncallArgumentNode arg3Node,
                @Cached CExtDowncallArgumentNode arg4Node,
                @Cached CExtDowncallArgumentNode arg5Node,
                @Cached CExtDowncallArgumentNode arg6Node,
                @Cached CExtDowncallArgumentNode arg7Node,
                @Cached CExtDowncallArgumentNode arg8Node,
                @Cached CExtDowncallArgumentNode arg9Node,
                @Cached CExtDowncallArgumentNode arg10Node,
                @Cached CExtDowncallArgumentNode arg11Node,
                @Cached CExtDowncallArgumentNode arg12Node,
                @Cached CExtDowncallArgumentNode arg13Node,
                @Cached CExtDowncallArgumentNode arg14Node,
                @Cached CExtDowncallArgumentNode arg15Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            final long result = invokeL_LLLLLLLLLLLLLLLL(function, arg0Node.execute(a0), arg1Node.execute(a1), arg2Node.execute(a2), arg3Node.execute(a3), arg4Node.execute(a4), arg5Node.execute(a5), arg6Node.execute(a6), arg7Node.execute(a7), arg8Node.execute(a8), arg9Node.execute(a9), arg10Node.execute(a10), arg11Node.execute(a11), arg12Node.execute(a12), arg13Node.execute(a13), arg14Node.execute(a14), arg15Node.execute(a15));
            checkPendingException(exceptionProfile);
            return result;
        }
    }

    private static final MethodHandle HANDLE_L_LLLLLLLLLLLLLLLLL = FFMSupport.createDowncallHandle("L(LLLLLLLLLLLLLLLLL)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static long invokeL_LLLLLLLLLLLLLLLLL(long function, long a0, long a1, long a2, long a3, long a4, long a5, long a6, long a7, long a8, long a9, long a10, long a11, long a12, long a13, long a14, long a15, long a16) {
        try {
            return (long) HANDLE_L_LLLLLLLLLLLLLLLLL.invokeExact(function, a0, a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11, a12, a13, a14, a15, a16);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_l_lllllllllllllllll")
    public abstract static class InvokeL_LLLLLLLLLLLLLLLLLNode extends CExtInvokeNode {
        @Specialization
        long invoke(long function, Object a0, Object a1, Object a2, Object a3, Object a4, Object a5, Object a6, Object a7, Object a8, Object a9, Object a10, Object a11, Object a12, Object a13, Object a14, Object a15, Object a16,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached CExtDowncallArgumentNode arg1Node,
                @Cached CExtDowncallArgumentNode arg2Node,
                @Cached CExtDowncallArgumentNode arg3Node,
                @Cached CExtDowncallArgumentNode arg4Node,
                @Cached CExtDowncallArgumentNode arg5Node,
                @Cached CExtDowncallArgumentNode arg6Node,
                @Cached CExtDowncallArgumentNode arg7Node,
                @Cached CExtDowncallArgumentNode arg8Node,
                @Cached CExtDowncallArgumentNode arg9Node,
                @Cached CExtDowncallArgumentNode arg10Node,
                @Cached CExtDowncallArgumentNode arg11Node,
                @Cached CExtDowncallArgumentNode arg12Node,
                @Cached CExtDowncallArgumentNode arg13Node,
                @Cached CExtDowncallArgumentNode arg14Node,
                @Cached CExtDowncallArgumentNode arg15Node,
                @Cached CExtDowncallArgumentNode arg16Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            final long result = invokeL_LLLLLLLLLLLLLLLLL(function, arg0Node.execute(a0), arg1Node.execute(a1), arg2Node.execute(a2), arg3Node.execute(a3), arg4Node.execute(a4), arg5Node.execute(a5), arg6Node.execute(a6), arg7Node.execute(a7), arg8Node.execute(a8), arg9Node.execute(a9), arg10Node.execute(a10), arg11Node.execute(a11), arg12Node.execute(a12), arg13Node.execute(a13), arg14Node.execute(a14), arg15Node.execute(a15), arg16Node.execute(a16));
            checkPendingException(exceptionProfile);
            return result;
        }
    }

    private static final MethodHandle HANDLE_V_L = FFMSupport.createDowncallHandle("V(L)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static void invokeV_L(long function, long a0) {
        try {
            HANDLE_V_L.invokeExact(function, a0);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_v_l")
    public abstract static class InvokeV_LNode extends CExtInvokeNode {
        @Specialization
        Object invoke(long function, Object a0,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            invokeV_L(function, arg0Node.execute(a0));
            checkPendingException(exceptionProfile);
            return nil;
        }
    }

    private static final MethodHandle HANDLE_V_LL = FFMSupport.createDowncallHandle("V(LL)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static void invokeV_LL(long function, long a0, long a1) {
        try {
            HANDLE_V_LL.invokeExact(function, a0, a1);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_v_ll")
    public abstract static class InvokeV_LLNode extends CExtInvokeNode {
        @Specialization
        Object invoke(long function, Object a0, Object a1,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached CExtDowncallArgumentNode arg1Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            invokeV_LL(function, arg0Node.execute(a0), arg1Node.execute(a1));
            checkPendingException(exceptionProfile);
            return nil;
        }
    }

    private static final MethodHandle HANDLE_V_LLL = FFMSupport.createDowncallHandle("V(LLL)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static void invokeV_LLL(long function, long a0, long a1, long a2) {
        try {
            HANDLE_V_LLL.invokeExact(function, a0, a1, a2);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_v_lll")
    public abstract static class InvokeV_LLLNode extends CExtInvokeNode {
        @Specialization
        Object invoke(long function, Object a0, Object a1, Object a2,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached CExtDowncallArgumentNode arg1Node,
                @Cached CExtDowncallArgumentNode arg2Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            invokeV_LLL(function, arg0Node.execute(a0), arg1Node.execute(a1), arg2Node.execute(a2));
            checkPendingException(exceptionProfile);
            return nil;
        }
    }

    private static final MethodHandle HANDLE_V_LLLL = FFMSupport.createDowncallHandle("V(LLLL)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static void invokeV_LLLL(long function, long a0, long a1, long a2, long a3) {
        try {
            HANDLE_V_LLLL.invokeExact(function, a0, a1, a2, a3);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_v_llll")
    public abstract static class InvokeV_LLLLNode extends CExtInvokeNode {
        @Specialization
        Object invoke(long function, Object a0, Object a1, Object a2, Object a3,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached CExtDowncallArgumentNode arg1Node,
                @Cached CExtDowncallArgumentNode arg2Node,
                @Cached CExtDowncallArgumentNode arg3Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            invokeV_LLLL(function, arg0Node.execute(a0), arg1Node.execute(a1), arg2Node.execute(a2), arg3Node.execute(a3));
            checkPendingException(exceptionProfile);
            return nil;
        }
    }

    private static final MethodHandle HANDLE_V_LI = FFMSupport.createDowncallHandle("V(LI)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static void invokeV_LI(long function, long a0, int a1) {
        try {
            HANDLE_V_LI.invokeExact(function, a0, a1);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_v_li", lowerFixnum = 2)
    public abstract static class InvokeV_LINode extends CExtInvokeNode {
        @Specialization
        Object invoke(long function, Object a0, int a1,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            invokeV_LI(function, arg0Node.execute(a0), a1);
            checkPendingException(exceptionProfile);
            return nil;
        }
    }

    private static final MethodHandle HANDLE_I_LLL = FFMSupport.createDowncallHandle("I(LLL)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static int invokeI_LLL(long function, long a0, long a1, long a2) {
        try {
            return (int) HANDLE_I_LLL.invokeExact(function, a0, a1, a2);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_i_lll")
    public abstract static class InvokeI_LLLNode extends CExtInvokeNode {
        @Specialization
        int invoke(long function, Object a0, Object a1, Object a2,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached CExtDowncallArgumentNode arg1Node,
                @Cached CExtDowncallArgumentNode arg2Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            final int result = invokeI_LLL(function, arg0Node.execute(a0), arg1Node.execute(a1), arg2Node.execute(a2));
            checkPendingException(exceptionProfile);
            return result;
        }
    }

    private static final MethodHandle HANDLE_I_LLLL = FFMSupport.createDowncallHandle("I(LLLL)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static int invokeI_LLLL(long function, long a0, long a1, long a2, long a3) {
        try {
            return (int) HANDLE_I_LLLL.invokeExact(function, a0, a1, a2, a3);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_i_llll")
    public abstract static class InvokeI_LLLLNode extends CExtInvokeNode {
        @Specialization
        int invoke(long function, Object a0, Object a1, Object a2, Object a3,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached CExtDowncallArgumentNode arg1Node,
                @Cached CExtDowncallArgumentNode arg2Node,
                @Cached CExtDowncallArgumentNode arg3Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            final int result = invokeI_LLLL(function, arg0Node.execute(a0), arg1Node.execute(a1), arg2Node.execute(a2), arg3Node.execute(a3));
            checkPendingException(exceptionProfile);
            return result;
        }
    }

    private static final MethodHandle HANDLE_L_LILL = FFMSupport.createDowncallHandle("L(LILL)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static long invokeL_LILL(long function, long a0, int a1, long a2, long a3) {
        try {
            return (long) HANDLE_L_LILL.invokeExact(function, a0, a1, a2, a3);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_l_lill", lowerFixnum = 2)
    public abstract static class InvokeL_LILLNode extends CExtInvokeNode {
        @Specialization
        long invoke(long function, Object a0, int a1, Object a2, Object a3,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached CExtDowncallArgumentNode arg2Node,
                @Cached CExtDowncallArgumentNode arg3Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            final long result = invokeL_LILL(function, arg0Node.execute(a0), a1, arg2Node.execute(a2), arg3Node.execute(a3));
            checkPendingException(exceptionProfile);
            return result;
        }
    }

    private static final MethodHandle HANDLE_L_LLLI = FFMSupport.createDowncallHandle("L(LLLI)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static long invokeL_LLLI(long function, long a0, long a1, long a2, int a3) {
        try {
            return (long) HANDLE_L_LLLI.invokeExact(function, a0, a1, a2, a3);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_l_llli", lowerFixnum = 4)
    public abstract static class InvokeL_LLLINode extends CExtInvokeNode {
        @Specialization
        long invoke(long function, Object a0, Object a1, Object a2, int a3,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached CExtDowncallArgumentNode arg1Node,
                @Cached CExtDowncallArgumentNode arg2Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            final long result = invokeL_LLLI(function, arg0Node.execute(a0), arg1Node.execute(a1), arg2Node.execute(a2), a3);
            checkPendingException(exceptionProfile);
            return result;
        }
    }

    private static final MethodHandle HANDLE_L_LLLILL = FFMSupport.createDowncallHandle("L(LLLILL)");

    @TruffleBoundary(allowInlining = true, transferToInterpreterOnException = false)
    private static long invokeL_LLLILL(long function, long a0, long a1, long a2, int a3, long a4, long a5) {
        try {
            return (long) HANDLE_L_LLLILL.invokeExact(function, a0, a1, a2, a3, a4, a5);
        } catch (Throwable t) {
            throw CompilerDirectives.shouldNotReachHere(t);
        }
    }

    @Primitive(name = "cext_invoke_l_lllill", lowerFixnum = 4)
    public abstract static class InvokeL_LLLILLNode extends CExtInvokeNode {
        @Specialization
        long invoke(long function, Object a0, Object a1, Object a2, int a3, Object a4, Object a5,
                @Cached CExtDowncallArgumentNode arg0Node,
                @Cached CExtDowncallArgumentNode arg1Node,
                @Cached CExtDowncallArgumentNode arg2Node,
                @Cached CExtDowncallArgumentNode arg4Node,
                @Cached CExtDowncallArgumentNode arg5Node,
                @Cached InlinedBranchProfile exceptionProfile) {
            final long result = invokeL_LLLILL(function, arg0Node.execute(a0), arg1Node.execute(a1), arg2Node.execute(a2), a3, arg4Node.execute(a4), arg5Node.execute(a5));
            checkPendingException(exceptionProfile);
            return result;
        }
    }
}
// @formatter:on
