/*
 * Copyright (c) 2026 TruffleRuby contributors.
 * Copyright (c) 2018-2025 Oracle and/or its affiliates.
 * This code is released under a tri EPL/GPL/LGPL license.
 * You can use it, redistribute it and/or modify it under the terms of the:
 *
 * Eclipse Public License version 2.0, or
 * GNU General Public License version 2, or
 * GNU Lesser General Public License version 2.1.
 */
package org.truffleruby.shared;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;

/** The build information generated by the build_information mx project (see BuildInformationProject in
 * mx_truffleruby.py) in a {@code build-information.properties} file at the root of the TruffleRuby home. It is read
 * when the context is initialized (at image build time for pre-initialized contexts) rather than compiled in Java
 * sources, so it is up-to-date on every build without needing to recompile any Java sources. */
public final class BuildInformation {

    public static final String PROPERTIES_FILE = "build-information.properties";

    /** Used when there is no build-information.properties, which is only possible when running miniruby. The version
     * can be passed with -Dtruffleruby.version, which miniruby does because some code like lib/mri/strscan.rb needs a
     * meaningful RUBY_ENGINE_VERSION. */
    public static final BuildInformation UNKNOWN = new BuildInformation(
            System.getProperty("truffleruby.version", "unknown"), "unknown", false, "unknown", null, "");

    public final String truffleRubyVersion;
    public final String fullRevision;
    public final String shortRevision;
    public final boolean isDirty;
    public final String commitDate;
    /** The value of $TRUFFLERUBY_BUILD_NAME when building, or null if it was not set */
    public final String buildName;
    public final String kernelMajorVersion;

    private BuildInformation(
            String truffleRubyVersion,
            String fullRevision,
            boolean isDirty,
            String commitDate,
            String buildName,
            String kernelMajorVersion) {
        this.truffleRubyVersion = truffleRubyVersion;
        this.fullRevision = fullRevision;
        this.shortRevision = fullRevision.equals("unknown") ? "unknown" : fullRevision.substring(0, 8);
        this.isDirty = isDirty;
        this.commitDate = commitDate;
        this.buildName = buildName;
        this.kernelMajorVersion = kernelMajorVersion;
    }

    public static BuildInformation load(Path path) {
        String contents;
        try {
            contents = Files.readString(path);
        } catch (IOException e) {
            return UNKNOWN;
        }
        return parse(contents);
    }

    public static BuildInformation parse(String contents) {
        String truffleRubyVersion = null;
        String fullRevision = null;
        String isDirty = null;
        String commitDate = null;
        String buildName = null;
        String kernelMajorVersion = null;

        for (String line : contents.split("\n")) {
            final int equals = line.indexOf('=');
            if (equals < 0) {
                continue;
            }
            final String key = line.substring(0, equals);
            final String value = line.substring(equals + 1);
            switch (key) {
                case "truffleRubyVersion" -> truffleRubyVersion = value;
                case "fullRevision" -> fullRevision = value;
                case "isDirty" -> isDirty = value;
                case "commitDate" -> commitDate = value;
                case "buildName" -> buildName = value;
                case "kernelMajorVersion" -> kernelMajorVersion = value;
                default -> throw new Error("Unknown key in " + PROPERTIES_FILE + ": " + key);
            }
        }

        if (truffleRubyVersion == null || fullRevision == null || isDirty == null || commitDate == null ||
                kernelMajorVersion == null) {
            throw new Error("Missing keys in " + PROPERTIES_FILE);
        }

        return new BuildInformation(
                truffleRubyVersion,
                fullRevision,
                Boolean.parseBoolean(isDirty),
                commitDate,
                buildName,
                kernelMajorVersion);
    }

}
