# frozen_string_literal: true

# Copyright (c) 2026 TruffleRuby contributors
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# The specification of every native-to-Java upcall used by the C extension
# support library (src/main/c/cext/*.c). Consumed by tool/generate-cext-upcalls.rb
# to generate the C declarations, the C initialization function and the Java
# upcall targets. Every upcall has a primitive-only signature so FFM upcall
# stubs qualify for Native Image direct upcalls.
#
# Fields: [c_name, kind, return_carrier, argument_carriers]
# kind: :cext   = calls the Truffle::CExt method named c_name (Java carrier long)
#       :send   = calls the SEND_NAMES[c_name] method on the receiver, which is the
#                 first argument; the method name is a constant on the Java side
#       :invoke = dynamically-named method call: (receiver, method name, args...)
#
# Carriers:
#   V = VALUE (handle, long).  Unwrapped to a Ruby object for the call; the
#       result is wrapped back to a handle.
#   W = pre-wrapped VALUE result: the Ruby method already returns a wrapped
#       VALUE (Primitive.cext_wrap), only converted to a handle (return only).
#   B = Ruby true/false result converted to int 1/0 (return only).
#   I = int, L = long, D = double, O = void (return only)
#   P = native pointer (long); a returned Truffle::FFI::Pointer is converted to its address, nil to 0
#   F = native function pointer (long)
#   Y = Ruby ID (long); converted to/from Symbol on the Java side
#   A = VALUE array: expands to (const VALUE*, long) in C and (long, long) in Java

module CExtUpcalls
  # standard: [c_name, kind, ret, args]
  UPCALLS = [
    ["DBL2BIG", :cext, "V", "D"],
    ["RARRAY_PTR", :cext, "P", "V"],
    ["RB_ENC_CODERANGE", :cext, "I", "V"],
    ["RB_FLOAT_TYPE_P", :cext, "B", "V"],
    ["RB_TYPE_P", :cext, "B", "VI"],
    ["RDATA", :cext, "P", "V"],
    ["RFLOAT_VALUE", :cext, "D", "V"],
    ["RSTRING_PTR", :cext, "L", "V"],
    ["RTYPEDDATA", :cext, "P", "V"],
    ["RTYPEDDATA_P", :cext, "B", "V"],
    ["SYMBOL_P", :cext, "B", "V"],
    ["ascii8bit_encoding", :cext, "V", ""],
    ["cext_module_function", :cext, "O", "VY"],
    ["code_to_mbclen", :cext, "I", "LV"],
    ["ensure_class", :cext, "V", "VVV"],
    ["invoke0", :invoke, "V", ""],
    ["send0___allocate__", :send, "V", "V"],
    ["send0_alive_p", :send, "V", "V"],
    ["send0_ancestors", :send, "V", "V"],
    ["send0_b_ascii_compatible_p", :send, "B", "V"],
    ["send0_b_ascii_only_p", :send, "B", "V"],
    ["send0_b_dummy_p", :send, "B", "V"],
    ["send0_begin", :send, "V", "V"],
    ["send0_binmode", :send, "V", "V"],
    ["send0_class", :send, "V", "V"],
    ["send0_clear", :send, "V", "V"],
    ["send0_close", :send, "V", "V"],
    ["send0_closed_p", :send, "V", "V"],
    ["send0_current", :send, "V", "V"],
    ["send0_default_external", :send, "V", "V"],
    ["send0_default_internal", :send, "V", "V"],
    ["send0_delete_if", :send, "V", "V"],
    ["send0_denominator", :send, "V", "V"],
    ["send0_disable", :send, "V", "V"],
    ["send0_dup", :send, "V", "V"],
    ["send0_each", :send, "V", "V"],
    ["send0_enable", :send, "V", "V"],
    ["send0_enabled_p", :send, "V", "V"],
    ["send0_encoding", :send, "V", "V"],
    ["send0_end", :send, "V", "V"],
    ["send0_exclude_end_p", :send, "V", "V"],
    ["send0_flush", :send, "V", "V"],
    ["send0_getbyte", :send, "V", "V"],
    ["send0_gets", :send, "V", "V"],
    ["send0_i_arity", :send, "I", "V"],
    ["send0_i_bytesize", :send, "I", "V"],
    ["send0_imag", :send, "V", "V"],
    ["send0_inspect", :send, "V", "V"],
    ["send0_instance_methods", :send, "V", "V"],
    ["send0_intern", :send, "V", "V"],
    ["send0_keys", :send, "V", "V"],
    ["send0_l_hash", :send, "L", "V"],
    ["send0_l_size", :send, "L", "V"],
    ["send0_l_tv_nsec", :send, "L", "V"],
    ["send0_l_tv_sec", :send, "L", "V"],
    ["send0_l_tv_usec", :send, "L", "V"],
    ["send0_length", :send, "V", "V"],
    ["send0_members", :send, "V", "V"],
    ["send0_name", :send, "V", "V"],
    ["send0_now", :send, "V", "V"],
    ["send0_numerator", :send, "V", "V"],
    ["send0_o_lock", :send, "O", "V"],
    ["send0_o_pass", :send, "O", "V"],
    ["send0_o_unlock", :send, "O", "V"],
    ["send0_pop", :send, "V", "V"],
    ["send0_private_instance_methods", :send, "V", "V"],
    ["send0_protected_instance_methods", :send, "V", "V"],
    ["send0_public_instance_methods", :send, "V", "V"],
    ["send0_real", :send, "V", "V"],
    ["send0_reverse_bang", :send, "V", "V"],
    ["send0_shift", :send, "V", "V"],
    ["send0_size", :send, "V", "V"],
    ["send0_sort", :send, "V", "V"],
    ["send0_sort_bang", :send, "V", "V"],
    ["send0_superclass", :send, "V", "V"],
    ["send0_to_s", :send, "V", "V"],
    ["send0_uminus", :send, "V", "V"],
    ["send0_wakeup", :send, "V", "V"],
    ["send1_add_p", :send, "V", "VV"],
    ["send1_aref", :send, "V", "VV"],
    ["send1_b_eq", :send, "B", "VV"],
    ["send1_concat", :send, "V", "VV"],
    ["send1_delete", :send, "V", "VV"],
    ["send1_delete_at", :send, "V", "VV"],
    ["send1_delete_p", :send, "V", "VV"],
    ["send1_eq", :send, "V", "VV"],
    ["send1_extend_object", :send, "V", "VV"],
    ["send1_fetch", :send, "V", "VV"],
    ["send1_force_encoding", :send, "V", "VV"],
    ["send1_i_aref", :send, "I", "VV"],
    ["send1_i_cmp", :send, "I", "VV"],
    ["send1_include_p", :send, "V", "VV"],
    ["send1_instance_methods", :send, "V", "VV"],
    ["send1_join", :send, "V", "VV"],
    ["send1_lshift", :send, "V", "VV"],
    ["send1_new", :send, "V", "VV"],
    ["send1_o_include", :send, "O", "VV"],
    ["send1_o_p", :send, "O", "VV"],
    ["send1_o_prepend", :send, "O", "VV"],
    ["send1_o_private", :send, "O", "VV"],
    ["send1_o_protected", :send, "O", "VV"],
    ["send1_o_push", :send, "O", "VV"],
    ["send1_o_sleep", :send, "O", "VV"],
    ["send1_path", :send, "V", "VV"],
    ["send1_plus", :send, "V", "VV"],
    ["send1_private_instance_methods", :send, "V", "VV"],
    ["send1_protected_instance_methods", :send, "V", "VV"],
    ["send1_public_instance_methods", :send, "V", "VV"],
    ["send1_replace", :send, "V", "VV"],
    ["send1_rotate_bang", :send, "V", "VV"],
    ["send1_split", :send, "V", "VV"],
    ["send1_times", :send, "V", "VV"],
    ["send1_unshift", :send, "V", "VV"],
    ["send1_write", :send, "V", "VV"],
    ["send2_aref", :send, "V", "VVV"],
    ["send2_aset", :send, "V", "VVV"],
    ["send2_at", :send, "V", "VVV"],
    ["send2_b_const_defined_p", :send, "B", "VVV"],
    ["send2_byteslice", :send, "V", "VVV"],
    ["send2_compatible_p", :send, "V", "VVV"],
    ["send2_const_get", :send, "V", "VVV"],
    ["send2_o_aset", :send, "O", "VVV"],
    ["send2_o_throw", :send, "O", "VVV"],
    ["send2_open", :send, "V", "VVV"],
    ["send3_o_aset", :send, "O", "VVVV"],
    ["make_binary_if_not_ascii_only", :cext, "O", "V"],
    ["mark_object_on_call_exit", :cext, "O", "V"],
    ["rb_2scomp_bit_length", :cext, "I", "V"],
    ["rb_Array", :cext, "V", "V"],
    ["rb_Complex", :cext, "V", "VV"],
    ["rb_Float", :cext, "V", "V"],
    ["rb_Hash", :cext, "V", "V"],
    ["rb_Integer", :cext, "V", "V"],
    ["rb_Rational", :cext, "V", "VV"],
    ["rb_String", :cext, "V", "V"],
    ["rb_absint_bit_length", :cext, "I", "V"],
    ["rb_absint_singlebit_p", :cext, "I", "V"],
    ["rb_alias", :cext, "O", "VVV"],
    ["rb_any_to_s", :cext, "V", "V"],
    ["rb_apply", :cext, "V", "VVV"],
    ["rb_arity_error_string", :cext, "V", "III"],
    ["rb_array_len", :cext, "L", "V"],
    ["rb_ary_new", :cext, "V", ""],
    ["rb_ary_new_capa", :cext, "V", "L"],
    ["rb_ary_new_from_values", :cext, "V", "A"],
    ["rb_ascii8bit_encindex", :cext, "I", ""],
    ["rb_attr", :cext, "O", "VVIII"],
    ["rb_backref_get", :cext, "V", ""],
    ["rb_backref_set", :cext, "V", "V"],
    ["rb_big_cmp", :cext, "V", "VV"],
    ["rb_big_sign", :cext, "V", "V"],
    ["rb_block_call", :cext, "V", "VVVFP"],
    ["rb_block_proc", :cext, "V", ""],
    ["rb_bug", :cext, "O", "V"],
    ["rb_cFiber", :cext, "V", ""],
    ["rb_call_super", :cext, "V", "V"],
    ["rb_call_super_kw", :cext, "V", "V"],
    ["rb_catch_obj", :cext, "W", "VFP"],
    ["rb_check_convert_type", :cext, "V", "VVV"],
    ["rb_check_frozen", :cext, "O", "V"],
    ["rb_check_funcall", :cext, "V", "VVV"],
    ["rb_check_symbol_cstr", :cext, "V", "V"],
    ["rb_check_to_integer", :cext, "V", "VV"],
    ["rb_check_type", :cext, "O", "VI"],
    ["rb_class_get_superclass", :cext, "V", "V"],
    ["rb_class_inherited_p", :cext, "V", "VV"],
    ["rb_class_new", :cext, "V", "V"],
    ["rb_class_new_instance", :cext, "V", "VV"],
    ["rb_class_new_instance_kw", :cext, "V", "VV"],
    ["rb_class_of", :cext, "V", "V"],
    ["rb_class_real", :cext, "V", "V"],
    ["rb_cmpint", :cext, "I", "VVV"],
    ["rb_complex_new", :cext, "V", "VV"],
    ["rb_complex_polar", :cext, "V", "VV"],
    ["rb_complex_raw", :cext, "V", "VV"],
    ["rb_complex_set_imag", :cext, "V", "VV"],
    ["rb_complex_set_real", :cext, "V", "VV"],
    ["rb_const_defined_3f", :cext, "B", "VV"],
    ["rb_const_get", :cext, "V", "VV"],
    ["rb_const_get_from", :cext, "V", "VV"],
    ["rb_const_remove", :cext, "V", "VV"],
    ["rb_const_set", :cext, "O", "VVV"],
    ["rb_convert_to_encoding", :cext, "V", "V"],
    ["rb_convert_type", :cext, "V", "VVV"],
    ["rb_copy_generic_ivar", :cext, "O", "VV"],
    ["rb_cstr_to_dbl", :cext, "D", "VV"],
    ["rb_cstr_to_inum", :cext, "V", "VII"],
    ["rb_cv_get", :cext, "V", "VV"],
    ["rb_cv_set", :cext, "O", "VVV"],
    ["rb_cvar_defined", :cext, "V", "VV"],
    ["rb_cvar_get", :cext, "V", "VV"],
    ["rb_cvar_set", :cext, "O", "VVV"],
    ["rb_data_define_no_splat", :cext, "V", "VV"],
    ["rb_data_object_wrap", :cext, "V", "VPFF"],
    ["rb_data_typed_object_wrap", :cext, "V", "VPPFFF"],
    ["rb_debug_inspector_open_contexts_and_backtrace", :cext, "V", ""],
    ["rb_default_external_encoding", :cext, "V", ""],
    ["rb_default_internal_encoding", :cext, "V", ""],
    ["rb_default_rs", :cext, "V", ""],
    ["rb_define_alloc_func", :cext, "O", "VF"],
    ["rb_define_attr", :cext, "O", "VVII"],
    ["rb_define_class_under", :cext, "V", "VVV"],
    ["rb_define_dummy_encoding", :cext, "I", "V"],
    ["rb_define_hooked_variable", :cext, "O", "VPFF"],
    ["rb_define_method", :cext, "V", "VVFI"],
    ["rb_define_method_undefined", :cext, "V", "VV"],
    ["rb_define_module_under", :cext, "V", "VV"],
    ["rb_enc_alias", :cext, "V", "VV"],
    ["rb_enc_associate_index", :cext, "V", "VI"],
    ["rb_enc_check", :cext, "V", "VV"],
    ["rb_enc_codepoint_len", :cext, "V", "V"],
    ["rb_enc_coderange_clear", :cext, "V", "V"],
    ["rb_enc_find_index", :cext, "I", "V"],
    ["rb_enc_from_index", :cext, "V", "I"],
    ["rb_enc_from_native_encoding", :cext, "V", "L"],
    ["rb_enc_get", :cext, "V", "V"],
    ["rb_enc_get_index", :cext, "I", "V"],
    ["rb_enc_isalnum", :cext, "B", "IV"],
    ["rb_enc_isspace", :cext, "B", "IV"],
    ["rb_enc_left_char_head", :cext, "I", "VVL"],
    ["rb_enc_mbc_to_codepoint", :cext, "I", "V"],
    ["rb_enc_mbclen", :cext, "I", "V"],
    ["rb_enc_mbmaxlen", :cext, "I", "V"],
    ["rb_enc_mbminlen", :cext, "I", "V"],
    ["rb_enc_precise_mbclen", :cext, "I", "V"],
    ["rb_enc_set_index", :cext, "O", "VI"],
    ["rb_enc_str_coderange", :cext, "I", "V"],
    ["rb_enc_strlen", :cext, "L", "V"],
    ["rb_enc_to_index", :cext, "I", "V"],
    ["rb_ensure", :cext, "W", "FPFP"],
    ["rb_enumeratorize", :cext, "V", "VVV"],
    ["rb_enumeratorize_with_size", :cext, "V", "VVVP"],
    ["rb_equal", :cext, "V", "VV"],
    ["rb_errinfo", :cext, "V", ""],
    ["rb_error_frozen_object", :cext, "O", "V"],
    ["rb_eval_cmd_kw", :cext, "V", "VVV"],
    ["rb_eval_string", :cext, "V", "V"],
    ["rb_exc_raise", :cext, "O", "V"],
    ["rb_exc_set_message", :cext, "O", "VV"],
    ["rb_exec_recursive", :cext, "V", "FLP"],
    ["rb_f_global_variables", :cext, "V", ""],
    ["rb_f_notimplement", :cext, "V", ""],
    ["rb_f_sprintf", :cext, "V", "V"],
    ["rb_fatal", :cext, "O", "V"],
    ["rb_fiber_current", :cext, "V", ""],
    ["rb_fiber_new", :cext, "V", "FP"],
    ["rb_filesystem_encindex", :cext, "I", ""],
    ["rb_filesystem_encoding", :cext, "V", ""],
    ["rb_fix2str", :cext, "V", "VV"],
    ["rb_fix2uint", :cext, "L", "V"],
    ["rb_float_new", :cext, "V", "D"],
    ["rb_flt_rationalize", :cext, "V", "V"],
    ["rb_flt_rationalize_with_prec", :cext, "V", "VV"],
    ["rb_frame_this_func", :cext, "V", ""],
    ["rb_free_generic_ivar", :cext, "O", "V"],
    ["rb_fs", :cext, "V", ""],
    ["rb_funcall_with_block", :cext, "V", "VVAV"],
    ["rb_funcall_with_block_keywords", :cext, "V", "VVAV"],
    ["rb_funcallv", :cext, "V", "VVA"],
    ["rb_funcallv_keywords", :cext, "V", "VVA"],
    ["rb_funcallv_public", :cext, "V", "VVA"],
    ["rb_gc", :cext, "O", ""],
    ["rb_gc_disable", :cext, "V", ""],
    ["rb_gc_enable", :cext, "V", ""],
    ["rb_gc_latest_gc_info", :cext, "V", "V"],
    ["rb_gc_mark", :cext, "O", "L"],
    ["rb_gc_register_address", :cext, "O", "P"],
    ["rb_gc_register_mark_object", :cext, "O", "L"],
    ["rb_gc_unregister_address", :cext, "O", "P"],
    ["rb_get_alloc_func", :cext, "F", "V"],
    ["rb_gv_get", :cext, "V", "V"],
    ["rb_gv_set", :cext, "V", "VV"],
    ["rb_hash", :cext, "V", "V"],
    ["rb_hash_aref", :cext, "V", "VV"],
    ["rb_hash_foreach", :cext, "O", "VFP"],
    ["rb_hash_get_or_undefined", :cext, "V", "VV"],
    ["rb_hash_new", :cext, "V", ""],
    ["rb_hash_new_capa", :cext, "V", "L"],
    ["rb_hash_set_ifnone", :cext, "V", "VV"],
    ["rb_hash_start", :cext, "L", "L"],
    ["rb_id2str", :cext, "V", "V"],
    ["rb_id_attrset", :cext, "V", "V"],
    ["rb_ident_hash_new", :cext, "V", ""],
    ["rb_inspect", :cext, "V", "V"],
    ["rb_int_cmp", :cext, "I", "VV"],
    ["rb_id2sym", :cext, "V", "Y"],
    ["rb_int2big", :cext, "V", "L"],
    ["rb_int_positive_pow", :cext, "V", "VV"],
    ["rb_integer_bytes_string", :cext, "V", "VIIVVV"],
    ["rb_integer_type_p", :cext, "B", "V"],
    ["rb_intern", :cext, "V", "V"],
    ["rb_io_descriptor", :cext, "I", "V"],
    ["rb_io_get_io", :cext, "V", "V"],
    ["rb_io_get_write_io", :cext, "V", "V"],
    ["rb_io_mode", :cext, "I", "V"],
    ["rb_io_open_descriptor", :cext, "V", "VVVVVVVVV"],
    ["rb_io_path", :cext, "V", "V"],
    ["rb_io_print", :cext, "V", "VV"],
    ["rb_io_printf", :cext, "V", "VV"],
    ["rb_io_puts", :cext, "V", "VV"],
    ["rb_is_class_id", :cext, "B", "V"],
    ["rb_is_const_id", :cext, "B", "V"],
    ["rb_is_instance_id", :cext, "B", "V"],
    ["rb_iter_break_value", :cext, "O", "V"],
    ["rb_iterate", :cext, "V", "FPFP"],
    ["rb_ivar_count", :cext, "V", "V"],
    ["rb_ivar_defined", :cext, "V", "VV"],
    ["rb_ivar_foreach", :cext, "O", "VFP"],
    ["rb_ivar_get", :cext, "V", "VV"],
    ["rb_ivar_lookup", :cext, "V", "VVV"],
    ["rb_ivar_set", :cext, "O", "VVV"],
    ["rb_java_class_of", :cext, "V", "V"],
    ["rb_java_to_string", :cext, "V", "V"],
    ["rb_jump_tag", :cext, "O", "I"],
    ["rb_keyword_given_p", :cext, "B", ""],
    ["rb_lastline_get", :cext, "V", ""],
    ["rb_lastline_set", :cext, "O", "V"],
    ["rb_locale_encindex", :cext, "I", ""],
    ["rb_locale_encoding", :cext, "V", ""],
    ["rb_make_backtrace", :cext, "V", ""],
    ["rb_make_exception", :cext, "V", "V"],
    ["rb_marshal_dump", :cext, "V", "VV"],
    ["rb_marshal_load", :cext, "V", "V"],
    ["rb_memerror", :cext, "O", ""],
    ["rb_method_boundp", :cext, "I", "VYI"],
    ["rb_module_new", :cext, "V", ""],
    ["rb_mutex_lock", :cext, "V", "V"],
    ["rb_mutex_locked_p", :cext, "V", "V"],
    ["rb_mutex_new", :cext, "V", ""],
    ["rb_mutex_sleep", :cext, "V", "VV"],
    ["rb_mutex_synchronize", :cext, "W", "VFP"],
    ["rb_mutex_trylock", :cext, "V", "V"],
    ["rb_mutex_unlock", :cext, "V", "V"],
    ["rb_nativethread_lock_destroy", :cext, "V", "V"],
    ["rb_nativethread_lock_initialize", :cext, "V", ""],
    ["rb_nativethread_self", :cext, "V", ""],
    ["rb_num2dbl", :cext, "D", "V"],
    ["rb_num2int", :cext, "I", "V"],
    ["rb_num2long", :cext, "L", "V"],
    ["rb_num2uint", :cext, "L", "V"],
    ["rb_num2ulong", :cext, "L", "V"],
    ["rb_num_coerce_bin", :cext, "V", "VVV"],
    ["rb_num_coerce_cmp", :cext, "V", "VVV"],
    ["rb_num_coerce_relop", :cext, "V", "VVV"],
    ["rb_obj_as_string", :cext, "V", "V"],
    ["rb_obj_call_init", :cext, "O", "VVV"],
    ["rb_obj_class", :cext, "V", "V"],
    ["rb_obj_classname", :cext, "V", "V"],
    ["rb_obj_clone", :cext, "V", "V"],
    ["rb_obj_dup", :cext, "V", "V"],
    ["rb_obj_encoding", :cext, "V", "V"],
    ["rb_obj_freeze", :cext, "V", "V"],
    ["rb_obj_frozen_p", :cext, "V", "V"],
    ["rb_obj_id", :cext, "V", "V"],
    ["rb_obj_instance_eval", :cext, "V", "VVV"],
    ["rb_obj_instance_variables", :cext, "V", "V"],
    ["rb_obj_is_instance_of", :cext, "V", "VV"],
    ["rb_obj_is_kind_of", :cext, "V", "VV"],
    ["rb_obj_method", :cext, "V", "VV"],
    ["rb_obj_method_arity", :cext, "I", "VV"],
    ["rb_obj_respond_to", :cext, "B", "VYI"],
    ["rb_output_fs", :cext, "V", ""],
    ["rb_output_rs", :cext, "V", ""],
    ["rb_path_to_class", :cext, "V", "V"],
    ["rb_proc_call", :cext, "V", "VV"],
    ["rb_proc_new", :cext, "W", "FP"],
    ["rb_protect", :cext, "W", "FPP"],
    ["rb_range_new", :cext, "V", "VVI"],
    ["rb_rational_new", :cext, "V", "VV"],
    ["rb_rational_raw", :cext, "V", "VV"],
    ["rb_reg_compile", :cext, "V", "VI"],
    ["rb_reg_match", :cext, "V", "VV"],
    ["rb_reg_match_pre", :cext, "V", "V"],
    ["rb_reg_new", :cext, "V", "VI"],
    ["rb_reg_new_str", :cext, "V", "VI"],
    ["rb_reg_nth_match", :cext, "V", "IV"],
    ["rb_reg_options", :cext, "V", "V"],
    ["rb_reg_regcomp", :cext, "V", "V"],
    ["rb_require", :cext, "V", "V"],
    ["rb_rescue", :cext, "W", "FPFP"],
    ["rb_rescue2", :cext, "W", "FPFPV"],
    ["rb_respond_to", :cext, "V", "VV"],
    ["rb_rs", :cext, "V", ""],
    ["rb_ruby_debug_ptr", :cext, "V", ""],
    ["rb_ruby_verbose_ptr", :cext, "V", ""],
    ["rb_set_end_proc", :cext, "O", "FP"],
    ["rb_set_errinfo", :cext, "O", "V"],
    ["rb_set_foreach", :cext, "O", "VFP"],
    ["rb_set_new", :cext, "V", ""],
    ["rb_singleton_class", :cext, "V", "V"],
    ["rb_sourcefile", :cext, "V", ""],
    ["rb_sourceline", :cext, "I", ""],
    ["rb_stderr", :cext, "V", ""],
    ["rb_stdin", :cext, "V", ""],
    ["rb_stdout", :cext, "V", ""],
    ["rb_str_append", :cext, "V", "VV"],
    ["rb_str_capacity", :cext, "L", "V"],
    ["rb_str_concat", :cext, "V", "VV"],
    ["rb_str_conv_enc_opts", :cext, "V", "VVVIV"],
    ["rb_str_encode", :cext, "V", "VVIV"],
    ["rb_str_format", :cext, "V", "VV"],
    ["rb_str_locktmp", :cext, "V", "V"],
    ["rb_str_new_frozen", :cext, "V", "V"],
    ["rb_str_new_native", :cext, "V", "PL"],
    ["rb_str_new_nul", :cext, "V", "L"],
    ["rb_str_offset", :cext, "L", "VL"],
    ["rb_str_resize", :cext, "V", "VL"],
    ["rb_str_set_len", :cext, "O", "VL"],
    ["rb_str_sublen", :cext, "L", "VL"],
    ["rb_str_unlocktmp", :cext, "V", "V"],
    ["rb_string_value_cstr_check", :cext, "V", "V"],
    ["rb_struct_aref", :cext, "V", "VV"],
    ["rb_struct_aset", :cext, "V", "VVV"],
    ["rb_struct_define_no_splat", :cext, "V", "VV"],
    ["rb_struct_define_under_no_splat", :cext, "V", "VVV"],
    ["rb_struct_getmember", :cext, "V", "VV"],
    ["rb_struct_initialize", :cext, "V", "VV"],
    ["rb_struct_new_no_splat", :cext, "V", "VV"],
    ["rb_struct_size", :cext, "I", "V"],
    ["rb_syserr_fail", :cext, "O", "IV"],
    ["rb_sym2id", :cext, "Y", "V"],
    ["rb_syserr_new", :cext, "V", "VV"],
    ["rb_thread_alone", :cext, "I", ""],
    ["rb_thread_call_with_gvl", :cext, "P", "FP"],
    ["rb_thread_call_without_gvl", :cext, "P", "FPFP"],
    ["rb_thread_check_ints", :cext, "O", ""],
    ["rb_thread_create", :cext, "V", "FP"],
    ["rb_thread_fd_writable", :cext, "I", "I"],
    ["rb_thread_wait_fd", :cext, "I", "I"],
    ["rb_time_interval_acceptable", :cext, "O", "V"],
    ["rb_time_nano_new", :cext, "V", "LL"],
    ["rb_time_num_new", :cext, "V", "VV"],
    ["rb_time_timespec_new", :cext, "V", "LLIVV"],
    ["rb_to_encoding", :cext, "P", "V"],
    ["rb_to_encoding_index", :cext, "I", "V"],
    ["rb_to_int", :cext, "V", "V"],
    ["rb_to_symbol", :cext, "V", "V"],
    ["rb_tr_cext_lock_owned_p", :cext, "B", ""],
    ["rb_tr_code_to_mbc", :cext, "V", "VL"],
    ["rb_tr_default_alloc_func", :cext, "V", "V"],
    ["rb_tr_enc_is_unicode", :cext, "I", "V"],
    ["rb_tr_enc_mbc_case_fold", :cext, "V", "IVFP"],
    ["rb_tr_flags", :cext, "I", "V"],
    ["rb_tr_gc_guard", :cext, "O", "L"],
    ["rb_tr_io_create_and_attach_pointer", :cext, "P", "VL"],
    ["rb_tr_io_pointer", :cext, "P", "V"],
    ["rb_tr_log_warning", :cext, "O", "V"],
    ["rb_tr_not_implemented", :cext, "O", "V"],
    ["rb_tr_obj_equal", :cext, "V", "VV"],
    ["rb_tr_pointer", :cext, "V", "P"],
    ["rb_tr_set_default_alloc_func", :cext, "O", "VF"],
    ["rb_tr_set_flags", :cext, "O", "VL"],
    ["rb_tr_sprintf", :cext, "V", "VFV"],
    ["rb_tr_sprintf_types", :cext, "V", "V"],
    ["rb_tr_static_native_string", :cext, "V", "LLV"],
    ["rb_tr_str_capa_resize", :cext, "O", "VL"],
    ["rb_tr_temporary_native_string", :cext, "V", "PLV"],
    ["rb_tr_warn", :cext, "V", "V"],
    ["rb_tr_warn_category", :cext, "V", "VV"],
    ["rb_tracepoint_new", :cext, "V", "IFP"],
    ["rb_type", :cext, "I", "V"],
    ["rb_ulong2num", :cext, "V", "L"],
    ["rb_undef", :cext, "O", "VV"],
    ["rb_undef_alloc_func", :cext, "O", "V"],
    ["rb_usascii_encindex", :cext, "I", ""],
    ["rb_utf8_encindex", :cext, "I", ""],
    ["rb_wait_for_single_fd", :cext, "I", "IILL"],
    ["rb_warning_category_enabled_p", :cext, "B", "V"],
    ["rb_yield", :cext, "V", "V"],
    ["rb_yield_splat", :cext, "V", "V"],
    ["ruby_native_thread_p", :cext, "B", ""],
    ["ruby_vm_at_exit", :cext, "O", "FP"],
    ["send_splatted", :cext, "V", "VVV"],
    ["set_thread_safe", :cext, "O", "I"],
    ["usascii_encoding", :cext, "V", ""],
    ["utf8_encoding", :cext, "V", ""],
    ["yield_no_block", :cext, "V", ""],
    ["zlib_get_crc_table", :cext, "V", ""],
  ]

  # send_* c_name => the method name called on the receiver (the first argument)
  SEND_NAMES = {
    "send0___allocate__" => "__allocate__",
    "send0_alive_p" => "alive?",
    "send0_ancestors" => "ancestors",
    "send0_b_ascii_compatible_p" => "ascii_compatible?",
    "send0_b_ascii_only_p" => "ascii_only?",
    "send0_b_dummy_p" => "dummy?",
    "send0_begin" => "begin",
    "send0_binmode" => "binmode",
    "send0_class" => "class",
    "send0_clear" => "clear",
    "send0_close" => "close",
    "send0_closed_p" => "closed?",
    "send0_current" => "current",
    "send0_default_external" => "default_external",
    "send0_default_internal" => "default_internal",
    "send0_delete_if" => "delete_if",
    "send0_denominator" => "denominator",
    "send0_disable" => "disable",
    "send0_dup" => "dup",
    "send0_each" => "each",
    "send0_enable" => "enable",
    "send0_enabled_p" => "enabled?",
    "send0_encoding" => "encoding",
    "send0_end" => "end",
    "send0_exclude_end_p" => "exclude_end?",
    "send0_flush" => "flush",
    "send0_getbyte" => "getbyte",
    "send0_gets" => "gets",
    "send0_i_arity" => "arity",
    "send0_i_bytesize" => "bytesize",
    "send0_imag" => "imag",
    "send0_inspect" => "inspect",
    "send0_instance_methods" => "instance_methods",
    "send0_intern" => "intern",
    "send0_keys" => "keys",
    "send0_l_hash" => "hash",
    "send0_l_size" => "size",
    "send0_l_tv_nsec" => "tv_nsec",
    "send0_l_tv_sec" => "tv_sec",
    "send0_l_tv_usec" => "tv_usec",
    "send0_length" => "length",
    "send0_members" => "members",
    "send0_name" => "name",
    "send0_now" => "now",
    "send0_numerator" => "numerator",
    "send0_o_lock" => "lock",
    "send0_o_pass" => "pass",
    "send0_o_unlock" => "unlock",
    "send0_pop" => "pop",
    "send0_private_instance_methods" => "private_instance_methods",
    "send0_protected_instance_methods" => "protected_instance_methods",
    "send0_public_instance_methods" => "public_instance_methods",
    "send0_real" => "real",
    "send0_reverse_bang" => "reverse!",
    "send0_shift" => "shift",
    "send0_size" => "size",
    "send0_sort" => "sort",
    "send0_sort_bang" => "sort!",
    "send0_superclass" => "superclass",
    "send0_to_s" => "to_s",
    "send0_uminus" => "-@",
    "send0_wakeup" => "wakeup",
    "send1_add_p" => "add?",
    "send1_aref" => "[]",
    "send1_b_eq" => "==",
    "send1_concat" => "concat",
    "send1_delete" => "delete",
    "send1_delete_at" => "delete_at",
    "send1_delete_p" => "delete?",
    "send1_eq" => "==",
    "send1_extend_object" => "extend_object",
    "send1_fetch" => "fetch",
    "send1_force_encoding" => "force_encoding",
    "send1_i_aref" => "[]",
    "send1_i_cmp" => "<=>",
    "send1_include_p" => "include?",
    "send1_instance_methods" => "instance_methods",
    "send1_join" => "join",
    "send1_lshift" => "<<",
    "send1_new" => "new",
    "send1_o_include" => "include",
    "send1_o_p" => "p",
    "send1_o_prepend" => "prepend",
    "send1_o_private" => "private",
    "send1_o_protected" => "protected",
    "send1_o_push" => "push",
    "send1_o_sleep" => "sleep",
    "send1_path" => "path",
    "send1_plus" => "+",
    "send1_private_instance_methods" => "private_instance_methods",
    "send1_protected_instance_methods" => "protected_instance_methods",
    "send1_public_instance_methods" => "public_instance_methods",
    "send1_replace" => "replace",
    "send1_rotate_bang" => "rotate!",
    "send1_split" => "split",
    "send1_times" => "*",
    "send1_unshift" => "unshift",
    "send1_write" => "write",
    "send2_aref" => "[]",
    "send2_aset" => "[]=",
    "send2_at" => "at",
    "send2_b_const_defined_p" => "const_defined?",
    "send2_byteslice" => "byteslice",
    "send2_compatible_p" => "compatible?",
    "send2_const_get" => "const_get",
    "send2_o_aset" => "[]=",
    "send2_o_throw" => "throw",
    "send2_open" => "open",
    "send3_o_aset" => "[]=",
  }

  # The carrier signatures of the native functions invoked from Ruby with Primitive.cext_invoke_*:
  # the rb_tr_setjmp_wrapper_* functions and the native helper functions of libtruffleruby.
  # tool/generate-cext-upcalls.rb generates one primitive per signature in CExtInvokePrimitives.java.
  DOWNCALL_SIGNATURES = [
    # rb_tr_setjmp_wrapper_pointer{1..16}_to_pointer: (target function, 1..16 VALUEs) -> VALUE,
    # also used by the native helper functions taking and returning pointers/VALUEs
    *(1..17).map { |n| "L(#{'L' * n})" },
    'V(L)',      # rb_tr_setjmp_wrapper_void_to_void, rb_tr_rdata_run_marker/finalizer
    'V(LL)',     # rb_tr_setjmp_wrapper_pointer1_to_void
    'V(LLL)',    # rb_tr_setjmp_wrapper_pointer2_to_void
    'V(LLLL)',   # rb_tr_setjmp_wrapper_pointer3_to_void
    'V(LI)',     # the ONIGENC_MBC_CASE_FOLD advance_p callback
    'I(LLL)',    # rb_tr_setjmp_wrapper_pointer2_to_int
    'I(LLLL)',   # rb_tr_setjmp_wrapper_pointer3_to_int
    'L(LILL)',   # rb_tr_setjmp_wrapper_int_pointer2_to_pointer
    'L(LLLI)',   # rb_tr_setjmp_wrapper_pointer2_int_to_pointer
    'L(LLLILL)', # rb_tr_setjmp_wrapper_pointer2_int_pointer2_to_pointer
  ]

  # c_name => Truffle::CExt method name, where they differ
  RUBY_NAMES = {
    "rb_const_defined_3f" => "rb_const_defined?",
    "rb_tr_enc_mbc_case_fold" => "rb_tr_enc_mbc_case_fold_from_native",
    "rb_tr_sprintf" => "rb_tr_sprintf_from_native",
  }
end
