# frozen_string_literal: true

# Copyright (c) 2026 TruffleRuby contributors
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
# 1. Redistributions of source code must retain the above copyright notice, this
#    list of conditions and the following disclaimer.
#
# 2. Redistributions in binary form must reproduce the above copyright notice,
#    this list of conditions and the following disclaimer in the documentation
#    and/or other materials provided with the distribution.
#
# 3. Neither the name of the copyright holder nor the names of its
#    contributors may be used to endorse or promote products derived from
#    this software without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.

# GENERATED BY tool/generate-posix-functions.rb

module Truffle::POSIX
  def self.generated_posix_resolve_function(constant_name, method_name, native_name)
    function = Primitive.posix_resolve native_name if NATIVE
    if function
      const_set constant_name, function
    else
      const_set constant_name, nil
      define_singleton_method(method_name) do |*|
        raise NotImplementedError, "#{native_name} is not available"
      end
      Primitive.method_unimplement method(method_name)
    end
  end

  def self.chdir(a)
    a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      result = Primitive.posix_invoke_i_l(CHDIR_FUNCTION, a_address)
    ensure
      Primitive.io_thread_buffer_free(a_posix_string)
    end
    result
  end

  def self.chown(a, b, c)
    a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      result = Primitive.posix_invoke_i_lII(CHOWN_FUNCTION, a_address, b, c)
    ensure
      Primitive.io_thread_buffer_free(a_posix_string)
    end
    result
  end

  def self.chroot(a)
    a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      result = Primitive.posix_invoke_i_l(CHROOT_FUNCTION, a_address)
    ensure
      Primitive.io_thread_buffer_free(a_posix_string)
    end
    result
  end

  def self.truffleposix_clock_getres(a)
    Primitive.posix_invoke_l_i(TRUFFLEPOSIX_CLOCK_GETRES_FUNCTION, a)
  end

  def self.truffleposix_clock_gettime(a)
    Primitive.posix_invoke_l_i(TRUFFLEPOSIX_CLOCK_GETTIME_FUNCTION, a)
  end

  def self.close(a)
    Primitive.posix_invoke_i_i(CLOSE_FUNCTION, a)
  end

  def self.closedir(a)
    a_address = a.address
    Primitive.posix_invoke_i_l(CLOSEDIR_FUNCTION, a_address)
  end

  def self.dirfd(a)
    a_address = a.address
    Primitive.posix_invoke_i_l(DIRFD_FUNCTION, a_address)
  end

  def self.dup(a)
    Primitive.posix_invoke_i_i(DUP_FUNCTION, a)
  end

  def self.dup2(a, b)
    Primitive.posix_invoke_i_ii(DUP2_FUNCTION, a, b)
  end

  def self.dup3(a, b, c)
    Primitive.posix_invoke_i_iii(DUP3_FUNCTION, a, b, c)
  end

  def self.fchdir(a)
    Primitive.posix_invoke_i_i(FCHDIR_FUNCTION, a)
  end

  def self.fchown(a, b, c)
    Primitive.posix_invoke_i_iII(FCHOWN_FUNCTION, a, b, c)
  end

  def self.fcntl(a, b, c)
    Primitive.posix_invoke_i_iii(FCNTL_FUNCTION, a, b, c)
  end

  def self.fdopendir(a)
    Truffle::FFI::Pointer.new(Primitive.posix_invoke_l_i(FDOPENDIR_FUNCTION, a))
  end

  def self.flock(a, b)
    begin
      result = Primitive.posix_invoke_i_ii_blocking(FLOCK_FUNCTION, a, b)
    end while result == -1 and Errno.errno == Truffle::POSIX::EINTR
    result
  end

  def self.truffleposix_fstat(a, b)
    b_address = b.address
    Primitive.posix_invoke_i_il(TRUFFLEPOSIX_FSTAT_FUNCTION, a, b_address)
  end

  def self.truffleposix_fstat_size(a)
    Primitive.posix_invoke_l_i(TRUFFLEPOSIX_FSTAT_SIZE_FUNCTION, a)
  end

  def self.truffleposix_fstatat(a, b, c, d)
    b_posix_string = Primitive.io_thread_buffer_allocate(b.bytesize + 1)
    begin
      b_address = b_posix_string.address
      Primitive.pointer_write_string(b_address, b)
      c_address = c.address
      result = Primitive.posix_invoke_i_illi(TRUFFLEPOSIX_FSTATAT_FUNCTION, a, b_address, c_address, d)
    ensure
      Primitive.io_thread_buffer_free(b_posix_string)
    end
    result
  end

  def self.truffleposix_fstatat_size(a, b, c)
    b_posix_string = Primitive.io_thread_buffer_allocate(b.bytesize + 1)
    begin
      b_address = b_posix_string.address
      Primitive.pointer_write_string(b_address, b)
      result = Primitive.posix_invoke_l_ili(TRUFFLEPOSIX_FSTATAT_SIZE_FUNCTION, a, b_address, c)
    ensure
      Primitive.io_thread_buffer_free(b_posix_string)
    end
    result
  end

  def self.posix_fadvise(a, b, c, d)
    Primitive.posix_invoke_i_illi(POSIX_FADVISE_FUNCTION, a, b, c, d)
  end

  def self.fsync(a)
    Primitive.posix_invoke_i_i(FSYNC_FUNCTION, a)
  end

  def self.ftruncate(a, b)
    Primitive.posix_invoke_i_il(FTRUNCATE_FUNCTION, a, b)
  end

  def self.getcwd(a, b)
    a_address = a.address
    result = Primitive.posix_invoke_l_lL(GETCWD_FUNCTION, a_address, b)
    result == 0 ? nil : Primitive.pointer_read_string_to_null(result, nil)
  end

  def self.ioctl(a, b, c)
    c_address = c.address
    Primitive.posix_invoke_i_iLl(IOCTL_FUNCTION, a, b, c_address)
  end

  def self.isatty(a)
    Primitive.posix_invoke_i_i(ISATTY_FUNCTION, a)
  end

  def self.lchown(a, b, c)
    a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      result = Primitive.posix_invoke_i_lII(LCHOWN_FUNCTION, a_address, b, c)
    ensure
      Primitive.io_thread_buffer_free(a_posix_string)
    end
    result
  end

  def self.link(a, b)
    posix_string_buffer, a_posix_string, b_posix_string = Truffle::FFI::Pool.stack_alloc(a.bytesize + 1, b.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      b_address = b_posix_string.address
      Primitive.pointer_write_string(b_address, b)
      result = Primitive.posix_invoke_i_ll(LINK_FUNCTION, a_address, b_address)
    ensure
      Truffle::FFI::Pool.stack_free(posix_string_buffer)
    end
    result
  end

  def self.lseek(a, b, c)
    Primitive.posix_invoke_l_ili(LSEEK_FUNCTION, a, b, c)
  end

  def self.truffleposix_lstat(a, b)
    a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      b_address = b.address
      result = Primitive.posix_invoke_i_ll(TRUFFLEPOSIX_LSTAT_FUNCTION, a_address, b_address)
    ensure
      Primitive.io_thread_buffer_free(a_posix_string)
    end
    result
  end

  def self.truffleposix_lutimes(a, b, c, d, e)
    a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      result = Primitive.posix_invoke_i_llili(TRUFFLEPOSIX_LUTIMES_FUNCTION, a_address, b, c, d, e)
    ensure
      Primitive.io_thread_buffer_free(a_posix_string)
    end
    result
  end

  def self.mmap(a, b, c, d, e, f)
    a_address = a.address
    Truffle::FFI::Pointer.new(Primitive.posix_invoke_l_lLiiil(MMAP_FUNCTION, a_address, b, c, d, e, f))
  end

  def self.munmap(a, b)
    a_address = a.address
    Primitive.posix_invoke_i_lL(MUNMAP_FUNCTION, a_address, b)
  end

  def self.opendir(a)
    a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      result = Primitive.posix_invoke_l_l(OPENDIR_FUNCTION, a_address)
    ensure
      Primitive.io_thread_buffer_free(a_posix_string)
    end
    Truffle::FFI::Pointer.new(result)
  end

  def self.pipe(a)
    a_address = a.address
    Primitive.posix_invoke_i_l(PIPE_FUNCTION, a_address)
  end

  def self.read(a, b, c)
    b_address = b.address
    begin
      result = Primitive.posix_invoke_l_ilL_blocking(READ_FUNCTION, a, b_address, c)
    end while result == -1 and Errno.errno == Truffle::POSIX::EINTR
    result
  end

  def self.pread(a, b, c, d)
    b_address = b.address
    begin
      result = Primitive.posix_invoke_l_ilLl_blocking(PREAD_FUNCTION, a, b_address, c, d)
    end while result == -1 and Errno.errno == Truffle::POSIX::EINTR
    result
  end

  def self.readlink(a, b, c)
    a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      b_address = b.address
      result = Primitive.posix_invoke_l_llL(READLINK_FUNCTION, a_address, b_address, c)
    ensure
      Primitive.io_thread_buffer_free(a_posix_string)
    end
    result
  end

  def self.realpath(a, b)
    a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      b_address = b.address
      result = Primitive.posix_invoke_l_ll(REALPATH_FUNCTION, a_address, b_address)
    ensure
      Primitive.io_thread_buffer_free(a_posix_string)
    end
    Truffle::FFI::Pointer.new(result)
  end

  def self.truffleposix_readdir_multiple(a, b, c, d, e)
    a_address = a.address
    e_address = e.address
    Primitive.posix_invoke_i_liiil(TRUFFLEPOSIX_READDIR_MULTIPLE_FUNCTION, a_address, b, c, d, e_address)
  end

  def self.truffleposix_readdir_name(a)
    a_address = a.address
    result = Primitive.posix_invoke_l_l(TRUFFLEPOSIX_READDIR_NAME_FUNCTION, a_address)
    result == 0 ? nil : Primitive.pointer_read_string_to_null(result, nil)
  end

  def self.rename(a, b)
    posix_string_buffer, a_posix_string, b_posix_string = Truffle::FFI::Pool.stack_alloc(a.bytesize + 1, b.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      b_address = b_posix_string.address
      Primitive.pointer_write_string(b_address, b)
      result = Primitive.posix_invoke_i_ll(RENAME_FUNCTION, a_address, b_address)
    ensure
      Truffle::FFI::Pool.stack_free(posix_string_buffer)
    end
    result
  end

  def self.truffleposix_rewinddir(a)
    a_address = a.address
    Primitive.posix_invoke_v_l(TRUFFLEPOSIX_REWINDDIR_FUNCTION, a_address)
  end

  def self.rmdir(a)
    a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      result = Primitive.posix_invoke_i_l(RMDIR_FUNCTION, a_address)
    ensure
      Primitive.io_thread_buffer_free(a_posix_string)
    end
    result
  end

  def self.seekdir(a, b)
    a_address = a.address
    Primitive.posix_invoke_v_ll(SEEKDIR_FUNCTION, a_address, b)
  end

  def self.truffleposix_stat(a, b)
    a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      b_address = b.address
      result = Primitive.posix_invoke_i_ll(TRUFFLEPOSIX_STAT_FUNCTION, a_address, b_address)
    ensure
      Primitive.io_thread_buffer_free(a_posix_string)
    end
    result
  end

  def self.truffleposix_stat_size(a)
    a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      result = Primitive.posix_invoke_l_l(TRUFFLEPOSIX_STAT_SIZE_FUNCTION, a_address)
    ensure
      Primitive.io_thread_buffer_free(a_posix_string)
    end
    result
  end

  def self.symlink(a, b)
    posix_string_buffer, a_posix_string, b_posix_string = Truffle::FFI::Pool.stack_alloc(a.bytesize + 1, b.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      b_address = b_posix_string.address
      Primitive.pointer_write_string(b_address, b)
      result = Primitive.posix_invoke_i_ll(SYMLINK_FUNCTION, a_address, b_address)
    ensure
      Truffle::FFI::Pool.stack_free(posix_string_buffer)
    end
    result
  end

  def self.telldir(a)
    a_address = a.address
    Primitive.posix_invoke_l_l(TELLDIR_FUNCTION, a_address)
  end

  def self.truncate(a, b)
    a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      result = Primitive.posix_invoke_i_ll(TRUNCATE_FUNCTION, a_address, b)
    ensure
      Primitive.io_thread_buffer_free(a_posix_string)
    end
    result
  end

  def self.unlink(a)
    a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      result = Primitive.posix_invoke_i_l(UNLINK_FUNCTION, a_address)
    ensure
      Primitive.io_thread_buffer_free(a_posix_string)
    end
    result
  end

  def self.truffleposix_utimes(a, b, c, d, e)
    a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      result = Primitive.posix_invoke_i_llili(TRUFFLEPOSIX_UTIMES_FUNCTION, a_address, b, c, d, e)
    ensure
      Primitive.io_thread_buffer_free(a_posix_string)
    end
    result
  end

  def self.write(a, b, c)
    b_address = b.address
    begin
      result = Primitive.posix_invoke_l_ilL_blocking(WRITE_FUNCTION, a, b_address, c)
    end while result == -1 and Errno.errno == Truffle::POSIX::EINTR
    result
  end

  def self.pwrite(a, b, c, d)
    b_address = b.address
    begin
      result = Primitive.posix_invoke_l_ilLl_blocking(PWRITE_FUNCTION, a, b_address, c, d)
    end while result == -1 and Errno.errno == Truffle::POSIX::EINTR
    result
  end

  def self.poll_single_fd_blocking_no_retry(a, b, c)
    Primitive.posix_invoke_i_iii_blocking(POLL_SINGLE_FD_BLOCKING_NO_RETRY_FUNCTION, a, b, c)
  end

  def self.getegid
    Primitive.posix_invoke_I(GETEGID_FUNCTION)
  end

  def self.getgid
    Primitive.posix_invoke_I(GETGID_FUNCTION)
  end

  def self.setresgid(a, b, c)
    Primitive.posix_invoke_i_III(SETRESGID_FUNCTION, a, b, c)
  end

  def self.setregid(a, b)
    Primitive.posix_invoke_i_II(SETREGID_FUNCTION, a, b)
  end

  def self.setegid(a)
    Primitive.posix_invoke_i_I(SETEGID_FUNCTION, a)
  end

  def self.setgid(a)
    Primitive.posix_invoke_i_I(SETGID_FUNCTION, a)
  end

  def self.geteuid
    Primitive.posix_invoke_I(GETEUID_FUNCTION)
  end

  def self.getuid
    Primitive.posix_invoke_I(GETUID_FUNCTION)
  end

  def self.setresuid(a, b, c)
    Primitive.posix_invoke_i_III(SETRESUID_FUNCTION, a, b, c)
  end

  def self.setreuid(a, b)
    Primitive.posix_invoke_i_II(SETREUID_FUNCTION, a, b)
  end

  def self.setruid(a)
    Primitive.posix_invoke_i_I(SETRUID_FUNCTION, a)
  end

  def self.seteuid(a)
    Primitive.posix_invoke_i_I(SETEUID_FUNCTION, a)
  end

  def self.setuid(a)
    Primitive.posix_invoke_i_I(SETUID_FUNCTION, a)
  end

  def self.getpid
    Primitive.posix_invoke_i(GETPID_FUNCTION)
  end

  def self.getppid
    Primitive.posix_invoke_i(GETPPID_FUNCTION)
  end

  def self.kill(a, b)
    Primitive.posix_invoke_i_ii(KILL_FUNCTION, a, b)
  end

  def self.getpgrp
    Primitive.posix_invoke_i(GETPGRP_FUNCTION)
  end

  def self.getpgid(a)
    Primitive.posix_invoke_i_i(GETPGID_FUNCTION, a)
  end

  def self.setpgid(a, b)
    Primitive.posix_invoke_i_ii(SETPGID_FUNCTION, a, b)
  end

  def self.setsid
    Primitive.posix_invoke_i(SETSID_FUNCTION)
  end

  def self.getsid(a)
    Primitive.posix_invoke_i_i(GETSID_FUNCTION, a)
  end

  def self.getgroups(a, b)
    b_address = b.address
    Primitive.posix_invoke_i_il(GETGROUPS_FUNCTION, a, b_address)
  end

  def self.setgroups(a, b)
    b_address = b.address
    Primitive.posix_invoke_i_Ll(SETGROUPS_FUNCTION, a, b_address)
  end

  def self.getrlimit(a, b)
    b_address = b.address
    Primitive.posix_invoke_i_il(GETRLIMIT_FUNCTION, a, b_address)
  end

  def self.setrlimit(a, b)
    b_address = b.address
    Primitive.posix_invoke_i_il(SETRLIMIT_FUNCTION, a, b_address)
  end

  def self.truffleposix_getrusage(a)
    a_address = a.address
    Primitive.posix_invoke_i_l(TRUFFLEPOSIX_GETRUSAGE_FUNCTION, a_address)
  end

  def self.truffleposix_getpriority(a, b)
    Primitive.posix_invoke_i_iI(TRUFFLEPOSIX_GETPRIORITY_FUNCTION, a, b)
  end

  def self.setpriority(a, b, c)
    Primitive.posix_invoke_i_iIi(SETPRIORITY_FUNCTION, a, b, c)
  end

  def self.execve(a, b, c)
    a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      b_address = b.address
      c_address = c.address
      result = Primitive.posix_invoke_i_lll(EXECVE_FUNCTION, a_address, b_address, c_address)
    ensure
      Primitive.io_thread_buffer_free(a_posix_string)
    end
    result
  end

  def self.truffleposix_posix_spawn(a, b, c, d, e, f, g, h)
    a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      b_address = b.address
      c_address = c.address
      e_address = e.address
      h_address = h.address
      result = Primitive.posix_invoke_i_llliliil(TRUFFLEPOSIX_POSIX_SPAWN_FUNCTION, a_address, b_address, c_address, d, e_address, f, g, h_address)
    ensure
      Primitive.io_thread_buffer_free(a_posix_string)
    end
    result
  end

  def self.truffleposix_waitpid(a, b, c)
    c_address = c.address
    begin
      result = Primitive.posix_invoke_i_iil_blocking(TRUFFLEPOSIX_WAITPID_FUNCTION, a, b, c_address)
    end while result == -1 and Errno.errno == Truffle::POSIX::EINTR
    result
  end

  def self.getenv(a)
    a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      result = Primitive.posix_invoke_l_l(GETENV_FUNCTION, a_address)
    ensure
      Primitive.io_thread_buffer_free(a_posix_string)
    end
    result == 0 ? nil : Primitive.pointer_read_string_to_null(result, nil)
  end

  def self.setenv_native(a, b, c)
    posix_string_buffer, a_posix_string, b_posix_string = Truffle::FFI::Pool.stack_alloc(a.bytesize + 1, b.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      b_address = b_posix_string.address
      Primitive.pointer_write_string(b_address, b)
      result = Primitive.posix_invoke_i_lli(SETENV_NATIVE_FUNCTION, a_address, b_address, c)
    ensure
      Truffle::FFI::Pool.stack_free(posix_string_buffer)
    end
    result
  end

  def self.unsetenv_native(a)
    a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      result = Primitive.posix_invoke_i_l(UNSETENV_NATIVE_FUNCTION, a_address)
    ensure
      Primitive.io_thread_buffer_free(a_posix_string)
    end
    result
  end

  def self.crypt(a, b)
    posix_string_buffer, a_posix_string, b_posix_string = Truffle::FFI::Pool.stack_alloc(a.bytesize + 1, b.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      b_address = b_posix_string.address
      Primitive.pointer_write_string(b_address, b)
      result = Primitive.posix_invoke_l_ll(CRYPT_FUNCTION, a_address, b_address)
    ensure
      Truffle::FFI::Pool.stack_free(posix_string_buffer)
    end
    result == 0 ? nil : Primitive.pointer_read_string_to_null(result, nil)
  end

  def self.truffleposix_get_current_user_home
    Truffle::FFI::Pointer.new(Primitive.posix_invoke_l(TRUFFLEPOSIX_GET_CURRENT_USER_HOME_FUNCTION))
  end

  def self.truffleposix_get_user_home(a)
    a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
    begin
      a_address = a_posix_string.address
      Primitive.pointer_write_string(a_address, a)
      result = Primitive.posix_invoke_l_l(TRUFFLEPOSIX_GET_USER_HOME_FUNCTION, a_address)
    ensure
      Primitive.io_thread_buffer_free(a_posix_string)
    end
    Truffle::FFI::Pointer.new(result)
  end

  def self.truffleposix_free(a)
    a_address = a.address
    Primitive.posix_invoke_v_l(TRUFFLEPOSIX_FREE_FUNCTION, a_address)
  end

  def self.truffleposix_page_size
    Primitive.posix_invoke_l(TRUFFLEPOSIX_PAGE_SIZE_FUNCTION)
  end

  def self.labs(a)
    Primitive.posix_invoke_l_l(LABS_FUNCTION, a)
  end

  if Truffle::Platform.linux?

    def self.chmod(a, b) # Linux
      a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
      begin
        a_address = a_posix_string.address
        Primitive.pointer_write_string(a_address, a)
        result = Primitive.posix_invoke_i_lI(CHMOD_FUNCTION, a_address, b)
      ensure
        Primitive.io_thread_buffer_free(a_posix_string)
      end
      result
    end

    def self.fchmod(a, b) # Linux
      Primitive.posix_invoke_i_iI(FCHMOD_FUNCTION, a, b)
    end

    def self.truffleposix_fstat_mode(a) # Linux
      Primitive.posix_invoke_I_i(TRUFFLEPOSIX_FSTAT_MODE_FUNCTION, a)
    end

    def self.truffleposix_fstatat_mode(a, b, c) # Linux
      b_posix_string = Primitive.io_thread_buffer_allocate(b.bytesize + 1)
      begin
        b_address = b_posix_string.address
        Primitive.pointer_write_string(b_address, b)
        result = Primitive.posix_invoke_I_ili(TRUFFLEPOSIX_FSTATAT_MODE_FUNCTION, a, b_address, c)
      ensure
        Primitive.io_thread_buffer_free(b_posix_string)
      end
      result
    end

    def self.lchmod(a, b) # Linux
      a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
      begin
        a_address = a_posix_string.address
        Primitive.pointer_write_string(a_address, a)
        result = Primitive.posix_invoke_i_lI(LCHMOD_FUNCTION, a_address, b)
      ensure
        Primitive.io_thread_buffer_free(a_posix_string)
      end
      result
    end

    def self.truffleposix_lstat_mode(a) # Linux
      a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
      begin
        a_address = a_posix_string.address
        Primitive.pointer_write_string(a_address, a)
        result = Primitive.posix_invoke_I_l(TRUFFLEPOSIX_LSTAT_MODE_FUNCTION, a_address)
      ensure
        Primitive.io_thread_buffer_free(a_posix_string)
      end
      result
    end

    def self.truffleposix_major(a) # Linux
      Primitive.posix_invoke_I_L(TRUFFLEPOSIX_MAJOR_FUNCTION, a)
    end

    def self.truffleposix_minor(a) # Linux
      Primitive.posix_invoke_I_L(TRUFFLEPOSIX_MINOR_FUNCTION, a)
    end

    def self.mkdir(a, b) # Linux
      a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
      begin
        a_address = a_posix_string.address
        Primitive.pointer_write_string(a_address, a)
        result = Primitive.posix_invoke_i_lI(MKDIR_FUNCTION, a_address, b)
      ensure
        Primitive.io_thread_buffer_free(a_posix_string)
      end
      result
    end

    def self.mkfifo(a, b) # Linux
      a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
      begin
        a_address = a_posix_string.address
        Primitive.pointer_write_string(a_address, a)
        result = Primitive.posix_invoke_i_lI(MKFIFO_FUNCTION, a_address, b)
      ensure
        Primitive.io_thread_buffer_free(a_posix_string)
      end
      result
    end

    def self.open(a, b, c) # Linux
      a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
      begin
        a_address = a_posix_string.address
        Primitive.pointer_write_string(a_address, a)
        result = Primitive.posix_invoke_i_liI(OPEN_FUNCTION, a_address, b, c)
      ensure
        Primitive.io_thread_buffer_free(a_posix_string)
      end
      result
    end

    def self.truffleposix_stat_mode(a) # Linux
      a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
      begin
        a_address = a_posix_string.address
        Primitive.pointer_write_string(a_address, a)
        result = Primitive.posix_invoke_I_l(TRUFFLEPOSIX_STAT_MODE_FUNCTION, a_address)
      ensure
        Primitive.io_thread_buffer_free(a_posix_string)
      end
      result
    end

    def self.umask(a) # Linux
      Primitive.posix_invoke_I_I(UMASK_FUNCTION, a)
    end

    def self.poll_blocking_no_retry(a, b, c) # Linux
      a_address = a.address
      Primitive.posix_invoke_i_lLi_blocking(POLL_BLOCKING_NO_RETRY_FUNCTION, a_address, b, c)
    end

  elsif Truffle::Platform.darwin?

    def self.chmod(a, b) # macOS
      a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
      begin
        a_address = a_posix_string.address
        Primitive.pointer_write_string(a_address, a)
        result = Primitive.posix_invoke_i_ls(CHMOD_FUNCTION, a_address, b)
      ensure
        Primitive.io_thread_buffer_free(a_posix_string)
      end
      result
    end

    def self.fchmod(a, b) # macOS
      Primitive.posix_invoke_i_is(FCHMOD_FUNCTION, a, b)
    end

    def self.truffleposix_fstat_mode(a) # macOS
      Primitive.posix_invoke_S_i(TRUFFLEPOSIX_FSTAT_MODE_FUNCTION, a)
    end

    def self.truffleposix_fstatat_mode(a, b, c) # macOS
      b_posix_string = Primitive.io_thread_buffer_allocate(b.bytesize + 1)
      begin
        b_address = b_posix_string.address
        Primitive.pointer_write_string(b_address, b)
        result = Primitive.posix_invoke_S_ili(TRUFFLEPOSIX_FSTATAT_MODE_FUNCTION, a, b_address, c)
      ensure
        Primitive.io_thread_buffer_free(b_posix_string)
      end
      result
    end

    def self.lchmod(a, b) # macOS
      a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
      begin
        a_address = a_posix_string.address
        Primitive.pointer_write_string(a_address, a)
        result = Primitive.posix_invoke_i_ls(LCHMOD_FUNCTION, a_address, b)
      ensure
        Primitive.io_thread_buffer_free(a_posix_string)
      end
      result
    end

    def self.truffleposix_lstat_mode(a) # macOS
      a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
      begin
        a_address = a_posix_string.address
        Primitive.pointer_write_string(a_address, a)
        result = Primitive.posix_invoke_S_l(TRUFFLEPOSIX_LSTAT_MODE_FUNCTION, a_address)
      ensure
        Primitive.io_thread_buffer_free(a_posix_string)
      end
      result
    end

    def self.truffleposix_major(a) # macOS
      Primitive.posix_invoke_I_i(TRUFFLEPOSIX_MAJOR_FUNCTION, a)
    end

    def self.truffleposix_minor(a) # macOS
      Primitive.posix_invoke_I_i(TRUFFLEPOSIX_MINOR_FUNCTION, a)
    end

    def self.mkdir(a, b) # macOS
      a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
      begin
        a_address = a_posix_string.address
        Primitive.pointer_write_string(a_address, a)
        result = Primitive.posix_invoke_i_ls(MKDIR_FUNCTION, a_address, b)
      ensure
        Primitive.io_thread_buffer_free(a_posix_string)
      end
      result
    end

    def self.mkfifo(a, b) # macOS
      a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
      begin
        a_address = a_posix_string.address
        Primitive.pointer_write_string(a_address, a)
        result = Primitive.posix_invoke_i_ls(MKFIFO_FUNCTION, a_address, b)
      ensure
        Primitive.io_thread_buffer_free(a_posix_string)
      end
      result
    end

    def self.open(a, b, c) # macOS
      a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
      begin
        a_address = a_posix_string.address
        Primitive.pointer_write_string(a_address, a)
        result = Primitive.posix_invoke_i_lis(OPEN_FUNCTION, a_address, b, c)
      ensure
        Primitive.io_thread_buffer_free(a_posix_string)
      end
      result
    end

    def self.truffleposix_stat_mode(a) # macOS
      a_posix_string = Primitive.io_thread_buffer_allocate(a.bytesize + 1)
      begin
        a_address = a_posix_string.address
        Primitive.pointer_write_string(a_address, a)
        result = Primitive.posix_invoke_S_l(TRUFFLEPOSIX_STAT_MODE_FUNCTION, a_address)
      ensure
        Primitive.io_thread_buffer_free(a_posix_string)
      end
      result
    end

    def self.umask(a) # macOS
      Primitive.posix_invoke_S_s(UMASK_FUNCTION, a)
    end

    def self.poll_blocking_no_retry(a, b, c) # macOS
      a_address = a.address
      Primitive.posix_invoke_i_lIi_blocking(POLL_BLOCKING_NO_RETRY_FUNCTION, a_address, b, c)
    end

  else
    raise 'unsupported POSIX platform'
  end

  Truffle::Boot.delay do
    generated_posix_resolve_function(:CHDIR_FUNCTION, :chdir, :tpe_chdir)
    generated_posix_resolve_function(:CHMOD_FUNCTION, :chmod, :tpe_chmod)
    generated_posix_resolve_function(:CHOWN_FUNCTION, :chown, :tpe_chown)
    generated_posix_resolve_function(:CHROOT_FUNCTION, :chroot, :tpe_chroot)
    generated_posix_resolve_function(:TRUFFLEPOSIX_CLOCK_GETRES_FUNCTION, :truffleposix_clock_getres, :tpe_truffleposix_clock_getres)
    generated_posix_resolve_function(:TRUFFLEPOSIX_CLOCK_GETTIME_FUNCTION, :truffleposix_clock_gettime, :tpe_truffleposix_clock_gettime)
    generated_posix_resolve_function(:CLOSE_FUNCTION, :close, :tpe_close)
    generated_posix_resolve_function(:CLOSEDIR_FUNCTION, :closedir, :tpe_closedir)
    generated_posix_resolve_function(:DIRFD_FUNCTION, :dirfd, :tpe_dirfd)
    generated_posix_resolve_function(:DUP_FUNCTION, :dup, :tpe_dup)
    generated_posix_resolve_function(:DUP2_FUNCTION, :dup2, :tpe_dup2)
    generated_posix_resolve_function(:DUP3_FUNCTION, :dup3, :tpe_dup3)
    generated_posix_resolve_function(:FCHDIR_FUNCTION, :fchdir, :tpe_fchdir)
    generated_posix_resolve_function(:FCHMOD_FUNCTION, :fchmod, :tpe_fchmod)
    generated_posix_resolve_function(:FCHOWN_FUNCTION, :fchown, :tpe_fchown)
    generated_posix_resolve_function(:FCNTL_FUNCTION, :fcntl, :tpe_fcntl)
    generated_posix_resolve_function(:FDOPENDIR_FUNCTION, :fdopendir, :tpe_fdopendir)
    generated_posix_resolve_function(:FLOCK_FUNCTION, :flock, :tpe_flock)
    generated_posix_resolve_function(:TRUFFLEPOSIX_FSTAT_FUNCTION, :truffleposix_fstat, :tpe_truffleposix_fstat)
    generated_posix_resolve_function(:TRUFFLEPOSIX_FSTAT_MODE_FUNCTION, :truffleposix_fstat_mode, :tpe_truffleposix_fstat_mode)
    generated_posix_resolve_function(:TRUFFLEPOSIX_FSTAT_SIZE_FUNCTION, :truffleposix_fstat_size, :tpe_truffleposix_fstat_size)
    generated_posix_resolve_function(:TRUFFLEPOSIX_FSTATAT_FUNCTION, :truffleposix_fstatat, :tpe_truffleposix_fstatat)
    generated_posix_resolve_function(:TRUFFLEPOSIX_FSTATAT_MODE_FUNCTION, :truffleposix_fstatat_mode, :tpe_truffleposix_fstatat_mode)
    generated_posix_resolve_function(:TRUFFLEPOSIX_FSTATAT_SIZE_FUNCTION, :truffleposix_fstatat_size, :tpe_truffleposix_fstatat_size)
    generated_posix_resolve_function(:POSIX_FADVISE_FUNCTION, :posix_fadvise, :tpe_posix_fadvise)
    generated_posix_resolve_function(:FSYNC_FUNCTION, :fsync, :tpe_fsync)
    generated_posix_resolve_function(:FTRUNCATE_FUNCTION, :ftruncate, :tpe_ftruncate)
    generated_posix_resolve_function(:GETCWD_FUNCTION, :getcwd, :tpe_getcwd)
    generated_posix_resolve_function(:IOCTL_FUNCTION, :ioctl, :tpe_ioctl)
    generated_posix_resolve_function(:ISATTY_FUNCTION, :isatty, :tpe_isatty)
    generated_posix_resolve_function(:LCHMOD_FUNCTION, :lchmod, :tpe_lchmod)
    generated_posix_resolve_function(:LCHOWN_FUNCTION, :lchown, :tpe_lchown)
    generated_posix_resolve_function(:LINK_FUNCTION, :link, :tpe_link)
    generated_posix_resolve_function(:LSEEK_FUNCTION, :lseek, :tpe_lseek)
    generated_posix_resolve_function(:TRUFFLEPOSIX_LSTAT_FUNCTION, :truffleposix_lstat, :tpe_truffleposix_lstat)
    generated_posix_resolve_function(:TRUFFLEPOSIX_LSTAT_MODE_FUNCTION, :truffleposix_lstat_mode, :tpe_truffleposix_lstat_mode)
    generated_posix_resolve_function(:TRUFFLEPOSIX_LUTIMES_FUNCTION, :truffleposix_lutimes, :tpe_truffleposix_lutimes)
    generated_posix_resolve_function(:TRUFFLEPOSIX_MAJOR_FUNCTION, :truffleposix_major, :tpe_truffleposix_major)
    generated_posix_resolve_function(:TRUFFLEPOSIX_MINOR_FUNCTION, :truffleposix_minor, :tpe_truffleposix_minor)
    generated_posix_resolve_function(:MKDIR_FUNCTION, :mkdir, :tpe_mkdir)
    generated_posix_resolve_function(:MKFIFO_FUNCTION, :mkfifo, :tpe_mkfifo)
    generated_posix_resolve_function(:MMAP_FUNCTION, :mmap, :tpe_mmap)
    generated_posix_resolve_function(:MUNMAP_FUNCTION, :munmap, :tpe_munmap)
    generated_posix_resolve_function(:OPEN_FUNCTION, :open, :tpe_open)
    generated_posix_resolve_function(:OPENDIR_FUNCTION, :opendir, :tpe_opendir)
    generated_posix_resolve_function(:PIPE_FUNCTION, :pipe, :tpe_pipe)
    generated_posix_resolve_function(:READ_FUNCTION, :read, :tpe_read)
    generated_posix_resolve_function(:PREAD_FUNCTION, :pread, :tpe_pread)
    generated_posix_resolve_function(:READLINK_FUNCTION, :readlink, :tpe_readlink)
    generated_posix_resolve_function(:REALPATH_FUNCTION, :realpath, :tpe_realpath)
    generated_posix_resolve_function(:TRUFFLEPOSIX_READDIR_MULTIPLE_FUNCTION, :truffleposix_readdir_multiple, :tpe_truffleposix_readdir_multiple)
    generated_posix_resolve_function(:TRUFFLEPOSIX_READDIR_NAME_FUNCTION, :truffleposix_readdir_name, :tpe_truffleposix_readdir_name)
    generated_posix_resolve_function(:RENAME_FUNCTION, :rename, :tpe_rename)
    generated_posix_resolve_function(:TRUFFLEPOSIX_REWINDDIR_FUNCTION, :truffleposix_rewinddir, :tpe_truffleposix_rewinddir)
    generated_posix_resolve_function(:RMDIR_FUNCTION, :rmdir, :tpe_rmdir)
    generated_posix_resolve_function(:SEEKDIR_FUNCTION, :seekdir, :tpe_seekdir)
    generated_posix_resolve_function(:TRUFFLEPOSIX_STAT_FUNCTION, :truffleposix_stat, :tpe_truffleposix_stat)
    generated_posix_resolve_function(:TRUFFLEPOSIX_STAT_MODE_FUNCTION, :truffleposix_stat_mode, :tpe_truffleposix_stat_mode)
    generated_posix_resolve_function(:TRUFFLEPOSIX_STAT_SIZE_FUNCTION, :truffleposix_stat_size, :tpe_truffleposix_stat_size)
    generated_posix_resolve_function(:SYMLINK_FUNCTION, :symlink, :tpe_symlink)
    generated_posix_resolve_function(:TELLDIR_FUNCTION, :telldir, :tpe_telldir)
    generated_posix_resolve_function(:TRUNCATE_FUNCTION, :truncate, :tpe_truncate)
    generated_posix_resolve_function(:UMASK_FUNCTION, :umask, :tpe_umask)
    generated_posix_resolve_function(:UNLINK_FUNCTION, :unlink, :tpe_unlink)
    generated_posix_resolve_function(:TRUFFLEPOSIX_UTIMES_FUNCTION, :truffleposix_utimes, :tpe_truffleposix_utimes)
    generated_posix_resolve_function(:WRITE_FUNCTION, :write, :tpe_write)
    generated_posix_resolve_function(:PWRITE_FUNCTION, :pwrite, :tpe_pwrite)
    generated_posix_resolve_function(:POLL_BLOCKING_NO_RETRY_FUNCTION, :poll_blocking_no_retry, :tpe_poll_blocking_no_retry)
    generated_posix_resolve_function(:POLL_SINGLE_FD_BLOCKING_NO_RETRY_FUNCTION, :poll_single_fd_blocking_no_retry, :tpe_poll_single_fd_blocking_no_retry)
    generated_posix_resolve_function(:GETEGID_FUNCTION, :getegid, :tpe_getegid)
    generated_posix_resolve_function(:GETGID_FUNCTION, :getgid, :tpe_getgid)
    generated_posix_resolve_function(:SETRESGID_FUNCTION, :setresgid, :tpe_setresgid)
    generated_posix_resolve_function(:SETREGID_FUNCTION, :setregid, :tpe_setregid)
    generated_posix_resolve_function(:SETEGID_FUNCTION, :setegid, :tpe_setegid)
    generated_posix_resolve_function(:SETGID_FUNCTION, :setgid, :tpe_setgid)
    generated_posix_resolve_function(:GETEUID_FUNCTION, :geteuid, :tpe_geteuid)
    generated_posix_resolve_function(:GETUID_FUNCTION, :getuid, :tpe_getuid)
    generated_posix_resolve_function(:SETRESUID_FUNCTION, :setresuid, :tpe_setresuid)
    generated_posix_resolve_function(:SETREUID_FUNCTION, :setreuid, :tpe_setreuid)
    generated_posix_resolve_function(:SETRUID_FUNCTION, :setruid, :tpe_setruid)
    generated_posix_resolve_function(:SETEUID_FUNCTION, :seteuid, :tpe_seteuid)
    generated_posix_resolve_function(:SETUID_FUNCTION, :setuid, :tpe_setuid)
    generated_posix_resolve_function(:GETPID_FUNCTION, :getpid, :tpe_getpid)
    generated_posix_resolve_function(:GETPPID_FUNCTION, :getppid, :tpe_getppid)
    generated_posix_resolve_function(:KILL_FUNCTION, :kill, :tpe_kill)
    generated_posix_resolve_function(:GETPGRP_FUNCTION, :getpgrp, :tpe_getpgrp)
    generated_posix_resolve_function(:GETPGID_FUNCTION, :getpgid, :tpe_getpgid)
    generated_posix_resolve_function(:SETPGID_FUNCTION, :setpgid, :tpe_setpgid)
    generated_posix_resolve_function(:SETSID_FUNCTION, :setsid, :tpe_setsid)
    generated_posix_resolve_function(:GETSID_FUNCTION, :getsid, :tpe_getsid)
    generated_posix_resolve_function(:GETGROUPS_FUNCTION, :getgroups, :tpe_getgroups)
    generated_posix_resolve_function(:SETGROUPS_FUNCTION, :setgroups, :tpe_setgroups)
    generated_posix_resolve_function(:GETRLIMIT_FUNCTION, :getrlimit, :tpe_getrlimit)
    generated_posix_resolve_function(:SETRLIMIT_FUNCTION, :setrlimit, :tpe_setrlimit)
    generated_posix_resolve_function(:TRUFFLEPOSIX_GETRUSAGE_FUNCTION, :truffleposix_getrusage, :tpe_truffleposix_getrusage)
    generated_posix_resolve_function(:TRUFFLEPOSIX_GETPRIORITY_FUNCTION, :truffleposix_getpriority, :tpe_truffleposix_getpriority)
    generated_posix_resolve_function(:SETPRIORITY_FUNCTION, :setpriority, :tpe_setpriority)
    generated_posix_resolve_function(:EXECVE_FUNCTION, :execve, :tpe_execve)
    generated_posix_resolve_function(:TRUFFLEPOSIX_POSIX_SPAWN_FUNCTION, :truffleposix_posix_spawn, :tpe_truffleposix_posix_spawn)
    generated_posix_resolve_function(:TRUFFLEPOSIX_WAITPID_FUNCTION, :truffleposix_waitpid, :tpe_truffleposix_waitpid)
    generated_posix_resolve_function(:GETENV_FUNCTION, :getenv, :tpe_getenv)
    generated_posix_resolve_function(:SETENV_NATIVE_FUNCTION, :setenv_native, :tpe_setenv_native)
    generated_posix_resolve_function(:UNSETENV_NATIVE_FUNCTION, :unsetenv_native, :tpe_unsetenv_native)
    generated_posix_resolve_function(:CRYPT_FUNCTION, :crypt, :tpe_crypt)
    generated_posix_resolve_function(:TRUFFLEPOSIX_GET_CURRENT_USER_HOME_FUNCTION, :truffleposix_get_current_user_home, :tpe_truffleposix_get_current_user_home)
    generated_posix_resolve_function(:TRUFFLEPOSIX_GET_USER_HOME_FUNCTION, :truffleposix_get_user_home, :tpe_truffleposix_get_user_home)
    generated_posix_resolve_function(:TRUFFLEPOSIX_FREE_FUNCTION, :truffleposix_free, :tpe_truffleposix_free)
    generated_posix_resolve_function(:TRUFFLEPOSIX_PAGE_SIZE_FUNCTION, :truffleposix_page_size, :tpe_truffleposix_page_size)
    generated_posix_resolve_function(:LABS_FUNCTION, :labs, :tpe_labs)
  end

end
