/*
 * Copyright (c) 2026 TruffleRuby contributors.
 * Copyright (c) 2017-2025 Oracle and/or its affiliates.
 * This code is released under a tri EPL/GPL/LGPL license.
 * You can use it, redistribute it and/or modify it under the terms of the:
 *
 * Eclipse Public License version 2.0, or
 * GNU General Public License version 2, or
 * GNU Lesser General Public License version 2.1.
 */

// GENERATED BY tool/generate-cext-constants.rb AND SHOULD NOT BE MODIFIED MANUALLY

#include <ruby.h>

VALUE rb_cArray;
VALUE rb_cBasicObject;
VALUE rb_cBinding;
VALUE rb_cClass;
VALUE rb_mComparable;
VALUE rb_cComplex;
VALUE rb_cDir;
VALUE rb_cEncoding;
VALUE rb_mEnumerable;
VALUE rb_cEnumerator;
VALUE rb_cArithSeq;
VALUE rb_cFalseClass;
VALUE rb_cFile;
VALUE rb_mFileTest;
VALUE rb_cStat;
VALUE rb_cFloat;
VALUE rb_mGC;
VALUE rb_cHash;
VALUE rb_cInteger;
VALUE rb_cIO;
VALUE rb_mKernel;
VALUE rb_cMatch;
VALUE rb_mMath;
VALUE rb_cMethod;
VALUE rb_cModule;
VALUE rb_cNilClass;
VALUE rb_cNumeric;
VALUE rb_cObject;
VALUE rb_cProc;
VALUE rb_mProcess;
VALUE rb_cRandom;
VALUE rb_cRange;
VALUE rb_cRational;
VALUE rb_cRegexp;
VALUE rb_cString;
VALUE rb_cStruct;
VALUE rb_cSymbol;
VALUE rb_cTime;
VALUE rb_cThread;
VALUE rb_cTrueClass;
VALUE rb_cUnboundMethod;
VALUE rb_eArgError;
VALUE rb_eEncodingError;
VALUE rb_eEOFError;
VALUE rb_mErrno;
VALUE rb_eException;
VALUE rb_eFloatDomainError;
VALUE rb_eFrozenError;
VALUE rb_eIndexError;
VALUE rb_eInterrupt;
VALUE rb_eIOError;
VALUE rb_eKeyError;
VALUE rb_eLoadError;
VALUE rb_eLocalJumpError;
VALUE rb_eMathDomainError;
VALUE rb_eEncCompatError;
VALUE rb_eNameError;
VALUE rb_eNoMemError;
VALUE rb_eNoMethodError;
VALUE rb_eNotImpError;
VALUE rb_eRangeError;
VALUE rb_eRegexpError;
VALUE rb_eRuntimeError;
VALUE rb_eScriptError;
VALUE rb_eSecurityError;
VALUE rb_eSignal;
VALUE rb_eStandardError;
VALUE rb_eStopIteration;
VALUE rb_eSyntaxError;
VALUE rb_eSystemCallError;
VALUE rb_eSystemExit;
VALUE rb_eSysStackError;
VALUE rb_eTypeError;
VALUE rb_eThreadError;
VALUE rb_eIOTimeoutError;
VALUE rb_mWaitReadable;
VALUE rb_mWaitWritable;
VALUE rb_eZeroDivError;
VALUE rb_eFatal;
VALUE rb_argv0;

// Constants are passed as an array of VALUE handles, in the order of GLOBAL_CONSTANT_NAMES
// in lib/truffle/truffle/cext_constants.rb (the order of this file).
void rb_tr_init_global_constants(const VALUE *constants) {
  rb_cArray = constants[0];
  rb_cBasicObject = constants[1];
  rb_cBinding = constants[2];
  rb_cClass = constants[3];
  rb_mComparable = constants[4];
  rb_cComplex = constants[5];
  rb_cDir = constants[6];
  rb_cEncoding = constants[7];
  rb_mEnumerable = constants[8];
  rb_cEnumerator = constants[9];
  rb_cArithSeq = constants[10];
  rb_cFalseClass = constants[11];
  rb_cFile = constants[12];
  rb_mFileTest = constants[13];
  rb_cStat = constants[14];
  rb_cFloat = constants[15];
  rb_mGC = constants[16];
  rb_cHash = constants[17];
  rb_cInteger = constants[18];
  rb_cIO = constants[19];
  rb_mKernel = constants[20];
  rb_cMatch = constants[21];
  rb_mMath = constants[22];
  rb_cMethod = constants[23];
  rb_cModule = constants[24];
  rb_cNilClass = constants[25];
  rb_cNumeric = constants[26];
  rb_cObject = constants[27];
  rb_cProc = constants[28];
  rb_mProcess = constants[29];
  rb_cRandom = constants[30];
  rb_cRange = constants[31];
  rb_cRational = constants[32];
  rb_cRegexp = constants[33];
  rb_cString = constants[34];
  rb_cStruct = constants[35];
  rb_cSymbol = constants[36];
  rb_cTime = constants[37];
  rb_cThread = constants[38];
  rb_cTrueClass = constants[39];
  rb_cUnboundMethod = constants[40];
  rb_eArgError = constants[41];
  rb_eEncodingError = constants[42];
  rb_eEOFError = constants[43];
  rb_mErrno = constants[44];
  rb_eException = constants[45];
  rb_eFloatDomainError = constants[46];
  rb_eFrozenError = constants[47];
  rb_eIndexError = constants[48];
  rb_eInterrupt = constants[49];
  rb_eIOError = constants[50];
  rb_eKeyError = constants[51];
  rb_eLoadError = constants[52];
  rb_eLocalJumpError = constants[53];
  rb_eMathDomainError = constants[54];
  rb_eEncCompatError = constants[55];
  rb_eNameError = constants[56];
  rb_eNoMemError = constants[57];
  rb_eNoMethodError = constants[58];
  rb_eNotImpError = constants[59];
  rb_eRangeError = constants[60];
  rb_eRegexpError = constants[61];
  rb_eRuntimeError = constants[62];
  rb_eScriptError = constants[63];
  rb_eSecurityError = constants[64];
  rb_eSignal = constants[65];
  rb_eStandardError = constants[66];
  rb_eStopIteration = constants[67];
  rb_eSyntaxError = constants[68];
  rb_eSystemCallError = constants[69];
  rb_eSystemExit = constants[70];
  rb_eSysStackError = constants[71];
  rb_eTypeError = constants[72];
  rb_eThreadError = constants[73];
  rb_eIOTimeoutError = constants[74];
  rb_mWaitReadable = constants[75];
  rb_mWaitWritable = constants[76];
  rb_eZeroDivError = constants[77];
  rb_eFatal = constants[78];
  rb_argv0 = constants[79];
}
