exclude :test_argument_errors, "TypeError expected but nothing was raised."
exclude :test_block_caller, "NoMethodError: undefined method `freed?' for an instance of Fiddle::Closure::BlockCaller"
exclude :test_bool, "NoMethodError: undefined method `freed?' for an instance of #<Class:0x428>"
exclude :test_call, "NoMethodError: undefined method `freed?' for an instance of #<Class:0x458>"
exclude :test_conversion_char, "NoMethodError: undefined method `freed?' for an instance of #<Class:0x488>"
exclude :test_conversion_int, "NoMethodError: undefined method `freed?' for an instance of #<Class:0x4c8>"
exclude :test_conversion_long, "NoMethodError: undefined method `freed?' for an instance of #<Class:0x508>"
exclude :test_conversion_long_long, "NoMethodError: undefined method `freed?' for an instance of #<Class:0x548>"
exclude :test_conversion_short, "NoMethodError: undefined method `freed?' for an instance of #<Class:0x588>"
exclude :test_conversion_unsigned_char, "NoMethodError: undefined method `freed?' for an instance of #<Class:0x5c8>"
exclude :test_conversion_unsigned_int, "NoMethodError: undefined method `freed?' for an instance of #<Class:0x608>"
exclude :test_conversion_unsigned_long, "NoMethodError: undefined method `freed?' for an instance of #<Class:0x648>"
exclude :test_conversion_unsigned_long_long, "NoMethodError: undefined method `freed?' for an instance of #<Class:0x688>"
exclude :test_conversion_unsigned_short, "NoMethodError: undefined method `freed?' for an instance of #<Class:0x6c8>"
exclude :test_free, "NoMethodError: undefined method `freed?' for an instance of #<Class:0x708>"
exclude :test_memsize_ruby_dev_42480, "NoMethodError: undefined method `freed?' for an instance of #<Class:0x738>"
exclude :test_returner, "NoMethodError: undefined method `freed?' for an instance of #<Class:0x768>"
