exclude :test_argument_count, "NoMethodError: undefined method `freed?' for an instance of #<Class:0x3c8>"
exclude :test_argument_errors, "[TypeError] exception expected, not #<NoMethodError: undefined method `map' for an instance of Integer>."
exclude :test_argument_type_conversion, "NotImplementedError: #<struct int=8, call_count=0> not implemented"
exclude :test_default_abi, "<:default_abi> expected but was <nil>."
exclude :test_function_as_method, "NotImplementedError: NotImplementedError"
exclude :test_function_as_proc, "NotImplementedError: NotImplementedError"
exclude :test_integer_pointer_conversion, "NotImplementedError: NotImplementedError"
exclude :test_name, "<\"sin\"> expected but was <nil>."
exclude :test_name_symbol, "<:sin> expected but was <nil>."
exclude :test_nogvl_poll, "very slow: 60.08s on truffleruby 34.0.0-dev-0b9bf975, like ruby 3.4.7, GraalVM CE JVM [x86_64-linux] with AMD Ryzen 7 9800X3D 8-Core Processor: ( 16 vCPUs)"
exclude :test_strcpy, "NotImplementedError: NotImplementedError"
