source 'https://rubygems.org'

gem 'psd_native', '1.1.3'
gem 'chunky_png', '1.3.6'
gem 'oily_png', '1.2.0'
gem 'bindata', '2.3.1'
gem 'hashie', '3.4.4'
gem 'psd-enginedata', '1.1.1'
gem 'psd', '2.1.2'

gem 'sorted_set'
