exclude :test_column, "Expected 0 to be nil."
exclude :test_dedent_string, "NoMethodError: undefined method 'dedent_string' for class Prism::Translation::Ripper"
exclude :test_encoding, "NoMethodError: undefined method 'encoding' for an instance of Prism::Translation::Ripper"
exclude :test_end_seen_eh, "TypeError: TypeError"
exclude :test_filename, "<\"ripper\"> expected but was <\"\">."
exclude :test_lineno, "Expected 1 to be nil."
exclude :test_new, "NoMethodError: undefined method 'state' for an instance of Prism::Translation::Ripper"
exclude :test_parse, "TypeError: TypeError"
exclude :test_regexp_with_option, "Expected #<Prism::Translation::Ripper:0xcc98"
exclude :test_state, "NoMethodError: undefined method 'state' for an instance of Prism::Translation::Ripper"
exclude :test_yydebug, "NoMethodError: undefined method 'yydebug' for an instance of Prism::Translation::Ripper"
exclude :test_yydebug_equals, "NoMethodError: undefined method 'yydebug=' for an instance of Prism::Translation::Ripper"
exclude :test_yydebug_ident, "NoMethodError: undefined method 'yydebug=' for an instance of Prism::Translation::Ripper"
exclude :test_yydebug_string, "NoMethodError: undefined method 'yydebug=' for an instance of Prism::Translation::Ripper"
